### ISSUE TITLE
Using Panasonic TV as SAT>IP source

### ISSUE THREAD

**Issue by bergvoll** [catalinii/minisatip#171] opened 2015-09-30 17:02 UTC
Hi all,

What i would like to do is use my Panasonic TX-49CX750 as SAT>IP source for minisatip, then get minisatip to decrypt the channels so i can connect the SAT>IP client in the same TV for watching. The TV got both a DVB-C/T and a DVB-S2 tuner, but i just want to use DVB-C.

I've tried using the following commands, without luck:
./minisatip -s dvbc:10.0.0.205:554 -o 127.0.0.1:15000
./minisatip -s dvbc:10.0.0.205:554 --s dvbs2:10.0.0.205:554 -e 0 -o 127.0.0.1:15000

when i look in the http status page, it shows no signal.

When using Tvheadend, the Panasonic SAT>IP server works without problems as a source and show up like this:
<img width="560" alt="skjermbilde 2015-09-30 kl 18 40 53" src="https://cloud.githubusercontent.com/assets/3657186/10200195/3caa0a48-67a5-11e5-9516-d4b0b42a3ed7.png">
<img width="248" alt="skjermbilde 2015-09-30 kl 18 41 31" src="https://cloud.githubusercontent.com/assets/3657186/10200189/3696c844-67a5-11e5-9bfc-d64bae11d27b.png">

The problem with Tvheadend is that it does not work as a SAT>IP server for the TV (cannot find all the channels, or playing any of them).

I also have no problem getting minisatip to work with the Panasonic SAT>IP client when i use a USB tuner as DVB-C source.

Any advice on how to get minisatip working with the Panasonic SAT>IP server as DVB-C source?

**Comment by catalinii** [comment] 2015-10-01 12:17
Hi,

I would recommend try tuning one channel and get the minisatip log (add -f -l -l )
The satip client was not tested with too many server so that could be also an issue...

Thanks

**Comment by bergvoll** [comment] 2015-10-01 18:41
Thanks for the reply.

I tried a bit more this evening with -l -l -l. Any hints in my log file?
http://pastebin.com/SuqwcP9y

**Comment by catalinii** [comment] 2015-10-03 04:12
Hi,

the problem is that the client is not compatible with yur TV. I will work on the next commit on this issue and you can test it...

Thanks

**Comment by bergvoll** [comment] 2015-10-04 08:18
Great!

Looking forward to testing it.

Thanks

**Comment by 9000h** [comment] 2015-10-05 08:27
looks like satip.c:352 
FILL("&plts=%s", tp->plts, PILOT_AUTO, get_pilot(tp->sys));
should be
FILL("&plts=%s", tp->plts, PILOT_AUTO, get_pilot(tp->plts));

**Comment by catalinii** [comment] 2015-10-05 13:19
Lol, i looked for it and at the first look i did not see it at all

**Comment by catalinii** [comment] 2015-10-05 13:20
Thank you

**Comment by bergvoll** [comment] 2015-10-05 14:52
Thank you for looking in to it. However, when i change that line, it still won't work.

Running minisatip like this: ./minisatip -s dvbc:10.0.0.205:554 -o 10.0.0.20:15000 -f -l -l -l
gives me this log: http://pastebin.com/nGcJ7A8P

**Comment by 9000h** [comment] 2015-10-05 15:49
well something is missing 

[05/10 16:50:15.14368]: Forcing session id 846930886 on stream 0
[05/10 16:50:15.14368]: No Transport header was specified, for sid 0
[05/10 16:50:15.14368]: reply -> 11 (10.0.0.205:51340) CL:0 :
RTSP/1.0 454 Session Not Found

**Comment by catalinii** [comment] 2015-10-06 05:14
Try the latest commit... 

thanks

**Comment by bergvoll** [comment] 2015-10-06 05:30
Unfortunately, still no luck.

http://paste.ubuntu.com/12695155/ (ran without the -o flag)

Thanks

**Comment by catalinii** [comment] 2015-10-06 06:34
Hi,

can you get an tcpdump -ni any port 554 -s 0 -A 
on the box with tvheadend that connects succesfully to your tv?

thanks

**Comment by bergvoll** [comment] 2015-10-06 06:53
Sure!

tcpdump while scanning muxes on tvheadend:
http://paste.ubuntu.com/12695339/

Hope this helps.

**Comment by 9000h** [comment] 2015-10-06 07:20
you shutdown tvheadend when you try with the Panasonic, so the tuner on the Panasonic server is free?

**Comment by bergvoll** [comment] 2015-10-06 07:22
Not shut down (using tvheadend with hdhomerun tuner), but i always have the Panasonic tuner/server disabled.

**Comment by 9000h** [comment] 2015-10-06 07:41
for the client connect it's may useful to look at https://github.com/rofafor/vdr-plugin-satip/blob/master/rtsp.c#L358

**Comment by lars18th** [comment] 2015-10-06 08:22
Hi,

As I see this trouble is similar (or identical) to #109 

Logs indicates the same: PLAY request fails (with "503 Service Unavailable" in Panasonic, and with "405 Method Not Allowed" in ALi), possibly because the lack of OPTIONS request before the SETUP request.

I suggest to send the OPTIONS command to the SAT>IP server when the minisatip receives the SETUP command from the client. Then the next PLAY command from the client will trigger the SETUP and PLAY commands from the minisatip to the SAT>IP server.

Regards!

**Comment by bergvoll** [comment] 2015-10-06 14:44
Just to make sure, I tried shutting down the TVheadend instance on my network, but it did not give any positive result.

**Comment by catalinii** [comment] 2015-10-07 12:33
Hi bergvoll,

I will close this issue as it is a duplicate of #109 (please follow that thread).

Thanks for understanding...

**Closed by catalinii** 2015-10-07 12:33 UTC
