### ISSUE TITLE
Fast parity changes in few milliseconds generate continuity errors 

### ISSUE THREAD

**Issue by brainstormi** [catalinii/minisatip#789] opened 2020-12-16 00:11 UTC
Hi... 
    I have seen some situations where I have some errors related to quick parity changes, like the ones in the logs below:

```
[16/12 01:09:18.336]: Parity change for TVE HD PMT 8, new active parity 0 pid 167 [47 00 A7 9B], last_parity_change 2712066
[16/12 01:09:18.337]: found CW: 1 for TVE HD PMT 8, pid 1038, master 8, 13804 ms ago, parity 0: 62 AC DC EA 27 B1 29 01
[16/12 01:09:18.338]: Parity change for TVE HD PMT 8, new active parity 1 pid 125 [47 00 7D D0], last_parity_change 2727087
[16/12 01:09:18.338]: found CW: -1 for TVE HD PMT 8, pid 1038, master 8, 0 ms ago, parity 1: not found
[16/12 01:09:18.338]: No CW found for pmt 8 parity 1 pid 1038, blen 1
[16/12 01:09:18.338]: Parity change for TVE HD PMT 8, new active parity 0 pid 167 [47 00 A7 9C], last_parity_change 2727088
[16/12 01:09:18.339]: found CW: 1 for TVE HD PMT 8, pid 1038, master 8, 13806 ms ago, parity 0: 62 AC DC EA 27 B1 29 01
[16/12 01:09:18.341]: PID Continuity error (adapter 0, pos 54): pid: 120, Expected CC: E, Actual CC: F, CC Before D
[16/12 01:09:18.588]: BW 534KB/s, Total BW: 1914 MB, ns/read 4578, r: 26, w: 31 fw: 0, tt: 119 ms
[16/12 01:09:19.268]: dvbapi: sending ECM key 0 for pid 0889 (2185), current ecm_parity = 1, previous parity 0, demux = 0, filter = 0, len = 142 [81 30 8B 07]
[16/12 01:09:19.280]: dvbapi read from socket 9 the following data (65 bytes), pos = 0, op 403C6F2B, key 0
[16/12 01:09:19.281]: dvbapi set filter for pid 0889 (2185), key 0, demux 0, filter 0 
[16/12 01:09:19.281]: dvbapi: filter for pid 2185 and key 0 already exists, fid 39
[16/12 01:09:19.584]: dvbapi read from socket 9 the following data (86 bytes), pos = 0, op 40106F86, key 0
[16/12 01:09:19.584]: dvbapi: received DVBAPI_CA_SET_DESCR, key 0 parity 1, index 0, CW OK: 2A 08 D1 03 5F 37 F7 8D
```
```
[16/12 01:11:18.407]: Parity change for TVE HD PMT 8, new active parity 0 pid 167 [47 00 A7 95], last_parity_change 2832135
[16/12 01:11:18.408]: found CW: 1 for TVE HD PMT 8, pid 1038, master 8, 13927 ms ago, parity 0: 19 73 D5 61 26 B3 E1 BA
[16/12 01:11:18.409]: Parity change for TVE HD PMT 8, new active parity 1 pid 124 [47 40 7C D9], last_parity_change 2847158
[16/12 01:11:18.409]: found CW: -1 for TVE HD PMT 8, pid 1038, master 8, 0 ms ago, parity 1: not found
[16/12 01:11:18.410]: No CW found for pmt 8 parity 1 pid 1038, blen 1
[16/12 01:11:18.411]: Parity change for TVE HD PMT 8, new active parity 0 pid 167 [47 00 A7 96], last_parity_change 2847160
[16/12 01:11:18.411]: found CW: 1 for TVE HD PMT 8, pid 1038, master 8, 13929 ms ago, parity 0: 19 73 D5 61 26 B3 E1 BA
[16/12 01:11:18.412]: Parity change for TVE HD PMT 8, new active parity 1 pid 125 [47 40 7D D9], last_parity_change 2847161
[16/12 01:11:18.412]: found CW: -1 for TVE HD PMT 8, pid 1038, master 8, 0 ms ago, parity 1: not found
[16/12 01:11:18.412]: No CW found for pmt 8 parity 1 pid 1038, blen 1
[16/12 01:11:18.412]: Parity change for TVE HD PMT 8, new active parity 0 pid 167 [47 00 A7 9A], last_parity_change 2847163
[16/12 01:11:18.412]: found CW: 1 for TVE HD PMT 8, pid 1038, master 8, 13931 ms ago, parity 0: 19 73 D5 61 26 B3 E1 BA
[16/12 01:11:19.183]: dvbapi: sending ECM key 0 for pid 0889 (2185), current ecm_parity = 1, previous parity 0, demux = 0, filter = 0, len = 142 [81 30 8B 07]
[16/12 01:11:19.191]: dvbapi read from socket 9 the following data (65 bytes), pos = 0, op 403C6F2B, key 0
[16/12 01:11:19.191]: dvbapi set filter for pid 0889 (2185), key 0, demux 0, filter 0 
[16/12 01:11:19.191]: dvbapi: filter for pid 2185 and key 0 already exists, fid 39
[16/12 01:11:19.235]: BW 785KB/s, Total BW: 2002 MB, ns/read 4820, r: 25, w: 30 fw: 0, tt: 120 ms
[16/12 01:11:19.441]: dvbapi read from socket 9 the following data (86 bytes), pos = 0, op 40106F86, key 0
[16/12 01:11:19.441]: dvbapi: received DVBAPI_CA_SET_DESCR, key 0 parity 1, index 0, CW OK: FF 00 BB BA A0 38 58 30
```

This usually causes audio glitches in the stream or continuity errors getting the image pixelated. Fortunately it reconnect itself in less than 1 second getting this time the correct CW from Oscam. I suppose the automatic recovery is possible thanks to the patch applied by @lars18th here #570  #. Tvh in the same situation causes an image freeze until next ECM, which is a lot more annoying.

Oscam replay is fast, around 300ms always, with no timeouts or not found keys, after checking the logs.

Why do these quickly changes in a few milliseconds happens? Is it an Oscam issue? Is there any way to filter them or delaying the request of a new key seeing that at the end Oscam always provide the correct one?.

Regards,

**Comment by catalinii** [comment] 2020-12-16 00:58
The issue is that there is no key for parity 1. Basically when the stream (TVE) switches to that parity all the packets are lost.

Generally is hard to identify which CW is the correct one for the packet (unless you brute force). Based on your logs it seems that the CW for the one of the partities is missing (that's why the packets are lost - generating CCs).
The only

**Comment by brainstormi** [comment] 2020-12-16 09:12
Hi @catalinii 
   _The only_...? It seems that your sentence got incomplete in the most interesting part :)
    I saw in Tvh there is one parameter to delay descramble X packets to avoid problems with delayed keys. Is there something similar that can be setup in minisatip to workaround this.
Regards,

**Comment by lars18th** [comment] 2020-12-16 10:22
Hi @brainstormi ,

From my experience with minisatip over some years, regarding the troubles with decoding, I want to comment two points that can, or cannot, be related with your issue:
1. The idea of delaying the descrambling of X packets (or delay them for T miliseconds) was proposed some time ago. Perhaps at some point @catalinii will implement it. The _real_ impact of this enhancement will be in the case where the decoding card is clearly slow. If your CAS system returns the key with sufficient time then no decoding errors will appear when the key changes.
2. In the other hand, I discovered that several CC errors when the decoding key changes are not directly related with the decoding algorithm but with the pid filtering. Some key managers enable/disables some pids when a key decoding fails. In this case the minisatip internal logic will pass these commands directly to the tuner. And in my case, that I only use external SAT>IP tuners this could generate troubles. I see that a lot of low quality STB with SAT>IP server support have troubles when a pid change message is received. And this can generate that some TS packets will be lost, generating CC errors in the stream. That's the reason for my patch regarding "delayed close of pids" (#668 and #730) thus alleviating the problem a little.

So, if you suffer glitches in the decoding generated by CC errors, please describe your environment and check that your physical card is not slow.

**Comment by brainstormi** [comment] 2020-12-16 11:39
Hi @lars18th 
    I have some kind of "hybrid" environment with 2 adapters, once available in local lan and the other reachable through wan in a remote location, to overcome some punctual issues with the signal at my home. It looks like:
```
                                                TCP(WAN)                                           TechniSat 
     TCP(LAN)                                  |--------> minisatip server (RAW TS (-E) ) ----> SkyStar USB 2 HD
TvH ----------> minisatip (proxy/decrypting)---|
                                               |--------> Xoro SatIp server 8100 (Quad tunner)
                                                UDP(LAN)
.
```

**Comment by lars18th** [comment] 2020-12-16 12:07
Hi @brainstormi ,

Ohh! That environment is complex. But, I'm using complex solutions too.

That's my point of view/opinion:
- I prefer to use `minisatip` as the _edge_ SAT>IP server, than the TvHeadEnd. I'm callig "egde SAT>IP server" to the process to which the SAT>IP clients are connecting.
- The SAT>IP protocol over WAN connections have very poor performance. Even using TCP sockets and the RTP-over-TCP transport.
- When transfering encrypted MPEG-TS services is preferable to do the decryption in the remote location and not in the edge.

Then my suggestions:
- Run a minisatip instance in the remote location where the TechniSat server is running, and decrypt in this zone the services.
- Create a reliable tunnel between the edge/local minisatip server and the remote one.
- Use the decrypting capabilities of minisatip only for the local Xoro SAT>IP server.
- Connect your SAT>IP clients directly to the local minisatip; and use the TvHeadEnd only as a client of the minisatip for manage recordings.

I hope this helps you.
Regards.

**Comment by brainstormi** [comment] 2020-12-16 16:23
Hi @lars18th 
      Thanks for your valuable feedback. Regarding my environment, latency between local and remote location is below 10ms and through a reliable link. Anyway I tested your suggestions but the problem persists. The CC errors discussed here are related to the "sync problems" between minisatip and dvbapi server, always happening when this ping-pong with parity changes in a few ms happens. The ones related to weak signal, network glitches... are isolated and very very low count.
       What has worked perfectly it's to move the decoding to TvH and enabling the descrambling buffer with default value (9000 packets), 0 CC errors in the last 3h when usually I should have around 30.
       So it seems that some implementation for buffering packets before descrambling them would be needed in minisatip side. Reviewing how it was done and fixed in Tvh doesn't look like an easy task neither. [Here ](https://tvheadend.org/issues/5036) the discussion about this same issue and its patching in Tvh.
Regards,

**Comment by 9000h** [comment] 2020-12-16 16:53
so for tvh the fix was https://github.com/tvheadend/tvheadend/commit/ed5fd630318e0ee469015cc7161265f01186f653 ?

**Comment by brainstormi** [comment] 2020-12-16 17:09
At least there is another commit since tvh version 4.3-1173~g6311cf7 trying to fix this problem, tvheadend/tvheadend@4b3b0aa being the first approach.

**Comment by lars18th** [comment] 2020-12-16 18:06
OK @brainstormi ,

Then I suggest to @catalinii to think about to introduce a similar workaround inside minisatip.

Regards.

**Comment by catalinii** [comment] 2020-12-29 17:36
I see tvh implements what I had in mind... checking if the key actually works. This may be the best option to prevent expiring keys too fast.
I will add it on my to do list.

**Comment by catalinii** [comment] 2021-04-09 16:11
Can you check with the latest master if this is an issue?

**Comment by brainstormi** [comment] 2021-12-01 23:59
Maybe too late reply. I just deployed back my previous setup for testing it and have it now up and running. I'll report here in a few days when I see how it behaves over time. @catalinii what has been changed? Any reference to a commit to take a look at it just for curiosity?

**Comment by brainstormi** [comment] 2022-03-07 21:31
From my end, I couldn't perceive differences from how tvheadned works now around the number of continuity errors, but it's true I didn't battletested so not sure if it could be a placebo effect.

**Comment by Jalle19** [comment] 2022-03-14 18:32
I think we should close this if there's no concrete problem anymore

**Comment by Jalle19** [comment] 2022-03-14 18:33
Please re-open if there's some new development

**Closed by Jalle19** 2022-03-14 18:33 UTC
