### ISSUE TITLE
Web Interface: STR and SNR no working

### ISSUE THREAD

**Issue by Javito68** [catalinii/minisatip#901] opened 2021-10-19 16:14 UTC
Hello everyone, I have the following problem:

  Version: Minisatip Version: 1.1.46 on debian 10
 Target: WinTV-dualHD
minisatip installed as a service according to file: autostart.readme

options file: /etc/minisatip.conf:
  SERVER_ARGS = "- x 8090 -M *: 1-1.6 -R / var / lib / minisatip / html /"

works ok, except STR and SNR progress bars (view file)
![minisatip2](https://user-images.githubusercontent.com/46301145/137950473-bd54e917-a283-4771-b102-28871451c6c0.JPG)
what is the problem?

Thanks!!!

**Comment by lars18th** [comment] 2021-10-21 07:33
Hi @Javito68 ,

> the two running at the same time, I observe that I receive values from the two tuners, what is the problem?

I feel I found the problem. Let me to explain why this happens:

- I've do a review of the "dvb5-zap" tool to compare how it gets the tunning values, compared with the minisatip. So I discovered this:

https://github.com/catalinii/minisatip/blob/74adf9665163b62f5f62fe210b6dff6999ccf02f/src/dvb.c#L1378

- And this is similar to the one done in the "dvb5-zap" tool:
https://github.com/gjasny/v4l-utils/blob/9f1d1e0cf8dbdcfb8bc6d817734d85417960a054/utils/dvb/dvbv5-zap.c#L396


So the problem is not that minisatip is using a different call. The problem is this line:
https://github.com/catalinii/minisatip/blob/74adf9665163b62f5f62fe210b6dff6999ccf02f/src/dvb.c#L1372

So, in fact minisatip is not getting _any_ tuner value when the DVB API is less than 5.10:
https://github.com/catalinii/minisatip/blob/74adf9665163b62f5f62fe210b6dff6999ccf02f/src/dvb.c#L1440-L1442

Then the solution is to implement the same strategy that does the "dvb5-zap" tool. That's to encapsulate the calls with the function `dvb_fe_retrieve_stats()`:
https://github.com/gjasny/v4l-utils/blob/cd138c90d94385a816fb463d47f62b21fdc29106/lib/libdvbv5/dvb-fe.c#L1077.
With this function if the reading checks first if the driver can provide the values or not.

As a resum: The "dvb5-zap" tool not fails getting values as it has a more complex implementation. The current minisatip implementation don't have support for tuner drivers with an API less than 5.10.

My suggestion is to change the current implementation supporting any DVB 5.x API, and checking the properties before the syscall. And take note that different tuners with different API could be enabled inside the same system. So checking the OS DVBAPIVERSION it's a but strategy.

I hope @catalinii will want to fix it.
Regards.

**Comment by lars18th** [comment] 2022-01-21 13:50
Hi @catalinii ,

This is and old issue. Please, could you please close it? Thank you.

**Comment by catalinii** [comment] 2022-01-21 17:30
Based on the code get_signal_new return -1 if the  version of dvb headers is < 5.10 which in turn disables the new API to get the signal values.

If the new signal API is disabled, minisatip will use the old API: https://github.com/catalinii/minisatip/blob/74adf9665163b62f5f62fe210b6dff6999ccf02f/src/dvb.c#L1459
I think providing minisatip logs with -l dvb argument would help

**Comment by Jalle19** [comment] 2022-08-17 13:03
> Hi @catalinii ,
> 
> This is and old issue. Please, could you please close it? Thank you.

Closing 😄

**Closed by Jalle19** 2022-08-17 13:03 UTC
