### ISSUE TITLE
satipc module has a limit of 38 adapters

### ISSUE THREAD

**Issue by jyrts** [catalinii/minisatip#1132] opened 2023-11-07 18:24 UTC
```
minisatip -R /root/minisatip/html -l general --logfile /tmp/minisatip.log --disable-dvb --disable-ssdp -A 0:0-7:0,1:8-15:0,2:16-23:0,3:24-31:0,4:32-39:0,5:40-47:0 \
-s 192.168.2.22 -s 192.168.2.22 -s 192.168.2.22 -s 192.168.2.22 -s 192.168.2.22 -s 192.168.2.22 -s 192.168.2.22 -s 192.168.2.22 \
-s 192.168.2.20 -s 192.168.2.20 -s 192.168.2.20 -s 192.168.2.20 -s 192.168.2.20 -s 192.168.2.20 -s 192.168.2.20 -s 192.168.2.20 \
-s 192.168.2.25 -s 192.168.2.25 -s 192.168.2.25 -s 192.168.2.25 -s 192.168.2.25 -s 192.168.2.25 -s 192.168.2.25 -s 192.168.2.25 \
-s 192.168.2.24 -s 192.168.2.24 -s 192.168.2.24 -s 192.168.2.24 -s 192.168.2.24 -s 192.168.2.24 -s 192.168.2.24 -s 192.168.2.24 \
-s 192.168.2.23 -s 192.168.2.23 -s 192.168.2.23 -s 192.168.2.23 -s 192.168.2.23 -s 192.168.2.23 -s 192.168.2.23 -s 192.168.2.23 \
-s 192.168.2.32 -s 192.168.2.32 -s 192.168.2.32 -s 192.168.2.32 -s 192.168.2.32 -s 192.168.2.32 -s 192.168.2.32 -s 192.168.2.32 \
```

[minisatip.log](https://github.com/catalinii/minisatip/files/13284575/minisatip.log)

**Comment by lars18th** [comment] 2023-11-08 16:31
Hi,

The bug is not "minisatip limited to 38 adapters". See the code:
https://github.com/catalinii/minisatip/blob/80578a2031b14a63e3a2204be064134fda7fa1a8/src/adapter.h#L8

The problem is "satipc module has a limit of 38 adapters". Please, change the name of the issue.

**Comment by lars18th** [comment] 2023-11-08 16:44
I suspect that this code is not receiving the "full list" of the servers pased by the command line:
https://github.com/catalinii/minisatip/blob/80578a2031b14a63e3a2204be064134fda7fa1a8/src/satipc.c#L1658-L1660

Please @jyrts try to print the content of the satip_servers var in the LOG and execute with your command line.

**Comment by catalinii** [comment] 2023-12-27 20:32
this issue should be fixed now.

**Closed** 2024-03-03 06:32 UTC
Labels: bug
