### ISSUE TITLE
Diseqc 1.1 support

### ISSUE THREAD

**Issue by TheTroll** [catalinii/minisatip#150] opened 2015-07-26 15:34 UTC
Hi,

are the diseqc commands supported by minisatip.
I have a diseqc with 1 to 8 outputs, can I use minisatip with it?

Thanks a lot

**Comment by TheTroll** [comment] 2015-07-26 15:39
In my comment I meant Diseqc 1.1 of course

**Comment by catalinii** [comment] 2015-07-28 06:11
Hi,

yes diseqc 1.0 (at least is supported) and the code allows just for 4 outputs.

I know diseqc 1.1 allows up to 16 different outputs, do you use more than 5 lnb connected to it ?

Currently uncommited diseqc message is not sent, but I can change that easily in the next commit and let me know how it works.

Thanks

**Comment by TheTroll** [comment] 2015-07-28 07:01
Hi,

what I use is a diseqc 1.1 with 8 inputs and 1 output.
This is direct 1.1 mode (so uncommited?) where i can control lnb from 1 to 8.

It would be so great if you could add an option to select among:
- diseqc 1.0
- diseqc 1.0+1.1
- diseqc 1.1

Thanks a lot in advance!

**Comment by catalinii** [comment] 2015-07-28 07:44
Do you have some tool that works with your switch ?
All I could find on a quick search was commited (1.0) and uncommited (1.1).
Thanks

**Comment by TheTroll** [comment] 2015-07-28 07:55
Well my enigma2 box does :D
I guess tvheadend as well!

What i need in my case is pure uncomitted command, can you quickly implement it ? it's just an index.

Thanks!!

**Comment by catalinii** [comment] 2015-07-28 08:39
Yeah I have added the uncommited support to the next commit.

**Comment by TheTroll** [comment] 2015-07-28 08:46
Cool!
Can it be setup from command line?
when will you push?

I can test a patch ?

**Comment by catalinii** [comment] 2015-07-28 09:14
It will use src= parameter from the URL to set the diseqc input, so no command line.

Probably this week/ early next week.
I need to check what I did last time as I was away for a week.
Thanks

**Comment by TheTroll** [comment] 2015-07-28 09:30
But how will it decide if it needs to send 1.0 or 1.1?
I use the mipsel version for vu+  btw

thx

**Comment by catalinii** [comment] 2015-07-28 10:46
I'll send both....

**Comment by TheTroll** [comment] 2015-07-28 12:08
Ok thanks! I am really looking forward to testing it

**Comment by TheTroll** [comment] 2015-07-29 12:29
Hey, I have the openpli-oe-core setup from git on my PC.
Could you please explain how i could compile minisatip with it ?

thx

**Comment by TheTroll** [comment] 2015-07-30 05:34
Hi Catalinii

so I tried your patch (already :) ) with -l -l -l and adding the uncmd in the log.
I still can't tune (using tvheadend in this case).

Here is the log http://pastebin.com/bPjaF5N1

Can you please have a look ?

Enigma2 works well with this transponder.

Thanks

**Comment by catalinii** [comment] 2015-07-30 05:37
From the log I see is sending src=1 whihc is 0 uncommited and 1 commited (position 1)

basically what you have in src / 4 is uncommited
src % 4 is commited

**Comment by TheTroll** [comment] 2015-07-30 05:39
But if you look for instance :+1: 
https://github.com/linuxstb/dvbtools/blob/master/dvbtune/diseqc.c

It looks like the uncommited command is simply 0x39 0xFn, where n is 0->15 respect to diseqc input 1->16

In my case, I am using only 1 diseqc in 1.1 mode, with 1->8 inputs

**Comment by TheTroll** [comment] 2015-07-30 05:40
But even not sending the committed command doesnt not help ...
I don't know how but enigma2 works just fine  :/

**Comment by TheTroll** [comment] 2015-07-30 05:41
Here is the enigma2 part that works (i think):

http://sourceforge.net/p/openpli/enigma2/ci/65b45f75e4c14174a580a5345b85408fad826895/

**Comment by catalinii** [comment] 2015-07-30 05:43
Try src=8

**Comment by catalinii** [comment] 2015-07-30 05:43
Sorry src=4

**Comment by TheTroll** [comment] 2015-07-30 05:44
you mean src=4 for diseqc position 1 ?

**Comment by TheTroll** [comment] 2015-07-30 05:50
I get this with src=4

[30/07 07:49:55.124477]: send_diseqc fd 8, pos = 3, pol = 0, hiband = 0, com => e0 10 38 fc 00, uncom => e0 10 39 f0 00

**Comment by TheTroll** [comment] 2015-07-30 05:52
the uncmd should not be f0, strange, let me check

**Comment by TheTroll** [comment] 2015-07-30 06:29
I think that what you implemented actually is diseqc 1.0 + 1.1
In my case, it's pure diseqc 1.1 with 1->8 commands ...

I hope you can sort something out :)

Thx

**Comment by catalinii** [comment] 2015-07-30 09:59
Hi,

I forgot that src gets decremented so you can try src=5

I looked previously to tvheadend and the sources above and it is all about uncommitted and committed.

As I said
(src-1) / 4 --> uncommitted  index
(src -1) % 4 --> committed index

Thanks

**Comment by TheTroll** [comment] 2015-07-30 11:30
Yes I tried this.
i changed my diseqc working mode to 1.0+1.1 but same issue.

BTw are you sure of your uncommited command:
- is the pol and hi/low really necessary?
- my diseqc doc says that it should be set to even value for 1-4 and odd value for 5-8, ( with commited value A B C D)

**Comment by TheTroll** [comment] 2015-07-30 11:37
By the way, i can code and compile for my vu+, so if you have some debugging ideas, please let
me know!
Maybe it's the a diseqc problem after all.. maybe a tuning issue.

Aso the tone burst should be configuration enalbe/disable i think

thx!!

**Comment by TheTroll** [comment] 2015-07-30 19:09
Hi,

after more investigation it seems that the problem now comes from the pid filtering.
After we setup a pid filter (0 fo instance), no data comes back from dvr0 as expected.
Femon says that the tp is tuned though.
Is there a chance that the pid filtering has a problem on the vu+ solo2 with minisatip ?

Thanks

**Comment by catalinii** [comment] 2015-08-01 01:55
Hi,

just to understand, what was the solution for the diseqc problem ?
Is there something that needs to be done additionally to resolve tuning problems ?

About demux, if I understand correctly, you have multiple (2?) demux devices?
If yes you can change in dvb_set_pid (dvc.c) and see if you get something out of dvr0.

Thanks

**Comment by TheTroll** [comment] 2015-08-02 09:24
Hi,

to be honest it does not work very well..
I made it send only the 0x39 command and it helped.

About the demuxes and fe, it's still unclear to me how it works, but using fe0 and dmx0 was ok.

Though, the pid filtering was very slow to start.

**Comment by catalinii** [comment] 2015-08-04 00:10
Hi,

you mean there is a difference when you send just 39 or when you send 38 and 39 ?

Basically my entire question is, what needs to be implemented on the diseqc part for your switch to be working (more specifically what diseqc commands needs to be sent).

About the pid filtering, did you find a better way of doing the things ?

Thanks

**Comment by TheTroll** [comment] 2015-08-04 20:11
A difference with just 0x39.

I need to do more tests to know .. the switching seemed ok with 0x39 only.
About pid filtering, no i did not :/

**Comment by 9000h** [comment] 2015-08-05 12:40
unfortunatly the normal diseqc is broken since VERSION_BUILD "45", but I do not have the time to look after it

**Comment by catalinii** [comment] 2015-08-11 03:30
I have added a new switch -d for diseqc.

By defa8ult Diseqc 1.0 works as previously, but you can change to be sent just uncommitted or just committed signals.

Please test and let me know.

**Comment by 9000h** [comment] 2015-08-11 20:17
will do so when I'm back home end of August

**Comment by TheTroll** [comment] 2015-08-27 08:41
Hey,

I tried it and there is a little typo + a misconfig of the uncmd.
here is fix:
http://pastebin.com/NEYXfPmC

**Comment by 9000h** [comment] 2015-08-27 08:46
I can confirm the default Diseqc 1.0 works as previously.

**Comment by catalinii** [comment] 2015-08-28 06:42
Let me know if this ok on 1.1

Thanks

**Comment by TheTroll** [comment] 2015-08-28 07:39
Hi Catalinii,

yes with the patch it works for me!

thx

**Comment by catalinii** [comment] 2015-08-30 02:57
Thanks, I will close this.

**Closed by catalinii** 2015-08-30 02:57 UTC
