### ISSUE TITLE
RECEIVED SIGNAL 11 - SP=0 IP=0

### ISSUE THREAD

**Issue by pbriesch** [catalinii/minisatip#133] opened 2015-06-19 22:35 UTC
Hello Catalin,

minisatip crashed. Please find the following log:
````
[20/06 00:30:04.734737]: starting init_hw 1
[20/06 00:30:04.734737]: detect_dvb_parameters (S)-> addpids=1010
[20/06 00:30:04.734738]: detect_dvb_parameters (E) -> src=-1, fe=-1, freq=-1, fec=-1, sr=-1, pol=-1, ro=-1, msys=-1, mtype=-1, plts=-1, bw=-1, inv=-1, pids=NULL - apids=1010 - dpids=NULL x_pmt=NULL
[20/06 00:30:04.734738]: Setup stream 0 parameters, sock_id 4, handle 7
[20/06 00:30:04.734738]: copy_dvb_param start -> src=2, fe=0, freq=11488000, fec=5, sr=27500000, pol=2, ro=3, msys=5, mtype=0, plts=2, bw=8000000, inv=2, pids=NULL, apids=NULL, dpids=NULL x_pmt=NULL
[20/06 00:30:04.734738]: copy_dvb_parameters -> src=2, fe=0, freq=11488000, fec=5 sr=27500000, pol=2, ro=3, msys=5, mtype=0, plts=2, bw=8000000, inv=2, pids=NULL, apids=1010, dpids=NULL x_pmt=NULL
[20/06 00:30:04.734738]: Play for stream 0, type 2, rsock 14, adapter 0, sock_id 4 handle 7
[20/06 00:30:04.734738]: setting DVB parameters for adapter 0 - master_sid 0 sid 0 old f:11488000
[20/06 00:30:04.734739]: copy_dvb_param start -> src=2, fe=0, freq=11488000, fec=5, sr=27500000, pol=2, ro=3, msys=5, mtype=0, plts=2, bw=8000000, inv=2, pids=NULL, apids=1010, dpids=NULL x_pmt=NULL
[20/06 00:30:04.734739]: copy_dvb_parameters -> src=2, fe=0, freq=11488000, fec=5 sr=27500000, pol=2, ro=3, msys=5, mtype=0, plts=2, bw=8000000, inv=2, pids=NULL, apids=1010, dpids=NULL x_pmt=NULL
[20/06 00:30:04.734739]: adding pids to adapter 0, sid 0, pids=1010
[20/06 00:30:04.734739]: found already existing pid 1010 flags 1
[20/06 00:30:04.734739]: not tuning for SID 0 (do_tune=0, master_sid=0)
[20/06 00:30:04.734739]: reply -> 7 (192.168.1.20:38022) CL:0 :
RTSP/1.0 200 OK
Date: Fri, Jun 19 22:30:04 2015 GMT
Session: 1804289383
Cseq: 318
RTP-Info: url=rtsp://192.168.1.103/stream=1;seq=734739;rtptime=1434753004
Range: npt=0.000-


[20/06 00:30:04.734763]: PMT pid: 0415 (1045), pmt_len 74, pi_len 34, channel id 1419 (5145)
[20/06 00:30:04.734763]: PI pos 0 caid 0100 => pid 0AF5 (2805)
[20/06 00:30:04.734763]: PI pos 19 caid 1813 => pid 0AF5 (2805)
[20/06 00:30:04.734763]: PI pos 28 caid 0B01 => pid 0A2D (2605)
[20/06 00:30:04.734763]: start_pi: 0 34 es[0]-> 9
[20/06 00:30:04.734764]: PMT pid 1045 - stream pid 0060 (96), type 4, es_len 6, pos 0, pi_len 34 old pmt -1, old pmt for this pid 0
[20/06 00:30:04.734764]: PMT pid 1045 - stream pid 0061 (97), type 4, es_len 6, pos 11, pi_len 34 old pmt -1, old pmt for this pid 0
[20/06 00:30:04.734764]: PMT pid 1045 - stream pid 00A4 (164), type 2, es_len 0, pos 22, pi_len 34 old pmt -1, old pmt for this pid 0
[20/06 00:30:04.734764]: PMT pid: 0412 (1042), pmt_len 126, pi_len 69, channel id 1416 (5142)
[20/06 00:30:04.734764]: PI pos 0 caid 0100 => pid 0AFC (2812)
[20/06 00:30:04.734764]: PI pos 19 caid 1813 => pid 0AFC (2812)
[20/06 00:30:04.734764]: PI pos 28 caid 0B01 => pid 0A34 (2612)
[20/06 00:30:04.734764]: PI pos 34 caid 0B00 => pid 0A52 (2642)
[20/06 00:30:04.734764]: PI pos 40 caid 0500 => pid 0EE4 (3812)
[20/06 00:30:04.734764]: PI pos 57 caid 1803 => pid 12CC (4812)
[20/06 00:30:04.734765]: PI pos 63 caid 1863 => pid 12FE (4862)
[20/06 00:30:04.734765]: start_pi: 0 69 es[0]-> 9
[20/06 00:30:04.734765]: PMT pid 1042 - stream pid 007C (124), type 4, es_len 6, pos 0, pi_len 69 old pmt -1, old pmt for this pid 0
[20/06 00:30:04.734765]: PMT pid 1042 - stream pid 007D (125), type 4, es_len 6, pos 11, pi_len 69 old pmt -1, old pmt for this pid 0
[20/06 00:30:04.734765]: PMT pid 1042 - stream pid 00AB (171), type 2, es_len 0, pos 22, pi_len 69 old pmt -1, old pmt for this pid 0
[20/06 00:30:04.734765]: PMT pid: 03FE (1022), pmt_len 196, pi_len 167, channel id 1360 (4960)
[20/06 00:30:04.734765]: PI pos 0 caid 4ABF => pid 1D77 (7543)
[20/06 00:30:04.734765]: PI pos 6 caid 1861 => pid 1770 (6000)
[20/06 00:30:04.734766]: PI pos 12 caid 0647 => pid 1ECD (7885)
[20/06 00:30:04.734766]: PI pos 18 caid 0B01 => pid 1EDD (7901)
[20/06 00:30:04.734766]: PI pos 24 caid 0100 => pid 1E16 (7702)
[20/06 00:30:04.734766]: PI pos 43 caid 0B02 => pid 1D78 (7544)
[20/06 00:30:04.734766]: PI pos 49 caid 0500 => pid 1ECF (7887)
[20/06 00:30:04.734766]: PI pos 66 caid 0500 => pid 1E0D (7693)
[20/06 00:30:04.734766]: PI pos 83 caid 1813 => pid 1E16 (7702)
[20/06 00:30:04.734766]: PI pos 92 caid 1803 => pid 1771 (6001)
[20/06 00:30:04.734766]: PI pos 98 caid 0628 => pid 1D75 (7541)
[20/06 00:30:04.734766]: PI pos 104 caid 1884 => pid 10CF (4303)
[20/06 00:30:04.734766]: PI pos 110 caid 1807 => pid 183B (6203)
[20/06 00:30:04.734766]: PI pos 116 caid 0604 => pid 157F (5503)
[20/06 00:30:04.734767]: PI pos 122 caid 0100 => pid 1196 (4502)
[20/06 00:30:04.734767]: PI pos 141 caid 1819 => pid 1196 (4502)
[20/06 00:30:04.734767]: PI pos 150 caid 0500 => pid 11A0 (4512)
[20/06 00:30:04.734767]: start_pi: 0 167 es[0]-> 9
[20/06 00:30:04.734767]: PMT pid 1022 - stream pid 0838 (2104), type 2, es_len 0, pos 0, pi_len 167 old pmt -1, old pmt for this pid 0
[20/06 00:30:04.734767]: utils.c:169 allocation_wrapper malloc allocated 1510 bytes at 0x9935db8
[20/06 00:30:04.734767]: utils.c:169 allocation_wrapper malloc allocated 1510 bytes at 0x99363a8
[20/06 00:30:04.734767]: utils.c:169 allocation_wrapper malloc allocated 1510 bytes at 0x9936998
[20/06 00:30:04.734768]: Start streaming for stream 0, len 1316 to handle 14 => 192.168.1.20:46329
[20/06 00:30:04.734799]: PMT pid: 0413 (1043), pmt_len 65, pi_len 6, channel id 1417 (5143)
[20/06 00:30:04.734799]: PI pos 0 caid 1884 => pid 0A35 (2613)
[20/06 00:30:04.734800]: start_pi: 0 6 es[0]-> 9
[20/06 00:30:04.734800]: PMT pid 1043 - stream pid 0080 (128), type 4, es_len 6, pos 0, pi_len 6 old pmt -1, old pmt for this pid 0
[20/06 00:30:04.734800]: PMT pid 1043 - stream pid 00AC (172), type 2, es_len 0, pos 11, pi_len 6 old pmt -1, old pmt for this pid 0
[20/06 00:30:04.734800]: PMT pid: 03EA (1002), pmt_len 134, pi_len 0, channel id 13EE (5102)
[20/06 00:30:04.734800]: PMT pid 1002 - stream pid 00A1 (161), type 2, es_len 0, pos 0, pi_len 0 old pmt -1, old pmt for this pid 0
[20/06 00:30:04.734801]: PMT pid: 03F0 (1008), pmt_len 85, pi_len 40, channel id 13F4 (5108)
[20/06 00:30:04.734801]: PI pos 0 caid 0100 => pid 0AF8 (2808)
[20/06 00:30:04.734801]: PI pos 19 caid 1813 => pid 0AF8 (2808)
[20/06 00:30:04.734801]: PI pos 28 caid 1803 => pid 12C8 (4808)
[20/06 00:30:04.734801]: PI pos 34 caid 1861 => pid 12E6 (4838)
[20/06 00:30:04.734802]: start_pi: 0 40 es[0]-> 9
[20/06 00:30:04.734802]: PMT pid 1008 - stream pid 00A7 (167), type 2, es_len 0, pos 0, pi_len 40 old pmt -1, old pmt for this pid 0
[20/06 00:30:04.734804]: get_signal took 2 ms for adapter 0 handle 8 (status: 31, ber: 0, strength:300, snr: 94, max_strength: 306, max_snr: 143 0)
[20/06 00:30:04.734847]: PMT pid: 0416 (1046), pmt_len 162, pi_len 34, channel id 141A (5146)
[20/06 00:30:04.734848]: PI pos 0 caid 0100 => pid 0AF6 (2806)
[20/06 00:30:04.734848]: PI pos 19 caid 1813 => pid 0AF6 (2806)
[20/06 00:30:04.734848]: PI pos 28 caid 0B01 => pid 0F06 (3846)
[20/06 00:30:04.734848]: start_pi: 0 34 es[0]-> 9
[20/06 00:30:04.734848]: PMT pid 1046 - stream pid 00AA (170), type 2, es_len 0, pos 0, pi_len 34 old pmt -1, old pmt for this pid 0
[20/06 00:30:04.734849]: utils.c:169 allocation_wrapper malloc allocated 1510 bytes at 0x9936f88
[20/06 00:30:04.734849]: RECEIVED SIGNAL 11 - SP=0 IP=0

[20/06 00:30:04.734850]: Obtained 10 stack frames.

[20/06 00:30:04.734851]: 0x805b3ad :
print_trace at /home/pbriesch/sat/minisatip/utils.c:355
[20/06 00:30:04.734920]: 0x805b4c8 :
posix_signal_handler at /home/pbriesch/sat/minisatip/utils.c:390 (discriminator 1)
[20/06 00:30:04.734932]: 0xb7796bc8 :
?? ??:0
[20/06 00:30:04.734941]: 0x805f5c0 :
crc32 at /home/pbriesch/sat/minisatip/tables.c:228
[20/06 00:30:04.734952]: 0x805f4a0 :
assemble_packet at /home/pbriesch/sat/minisatip/tables.c:211
[20/06 00:30:04.734964]: 0x805ea01 :
dvbapi_process_pmt at /home/pbriesch/sat/minisatip/dvbapi.c:835
[20/06 00:30:04.734975]: 0x805ff0e :
process_stream at /home/pbriesch/sat/minisatip/tables.c:416
[20/06 00:30:04.734986]: 0x8052327 :
read_dmx at /home/pbriesch/sat/minisatip/stream.c:861
[20/06 00:30:04.734998]: 0x804e56e :
select_and_execute at /home/pbriesch/sat/minisatip/socketworks.c:533
[20/06 00:30:04.735009]: 0x804c420 :
main at /home/pbriesch/sat/minisatip/minisatip.c:841 (discriminator 1)
pbriesch@ubuntu32:~/sat/minisatip$

**Comment by catalinii** [comment] 2015-06-20 11:25
Hi Paul,

Can this problem be reproduced at will?

I suppose this is on hotbird?

Thanks

**Comment by pbriesch** [comment] 2015-06-20 12:24
Yes, it's on hotbird. It has happened several times, but I don't know which button to push to trigger it. Please let me know what you need from me.

Regards, Paul

**Comment by catalinii** [comment] 2015-06-20 13:07
Thanks, I will try to reproduce it.

**Comment by catalinii** [comment] 2015-06-24 14:45
I was not able to reproduce this easily but I got one occurrence of it.

Will keep this open until I figure it out where it comes from.

**Comment by lars18th** [comment] 2015-07-09 16:46
@catalinii 

I post my troubles (crash) commented on #103 here because you reference it.

After checking last commit (v.0.3.45) I can say:

1) The program is more robust (don't crash) with frequencies with low signal. Excelent!

2) Even, when tunning these low signal frequencies, with only FTA programs, it seems to request some tokens/keys to the Oscam server. This is an error.

Can you provide some tweaks for (I prefer "c" option):

a) ignore not known CAs?
b) disable CA on some frequencies/tuners?
c) include more conservative detection of the encrypted programs?

In any case, the last commit improves much the stability.
Thank you!

**Comment by catalinii** [comment] 2015-07-10 08:58
Hi,

Please upload a log for 2,
I have the feeling is related with 103.

About the list CAs, generally oscam controlls that, as minisatip sends all the CAs to oscam and oscam manages which ecm needs to be sent to oscam.
For b seems similar with #123.
c) is clear that the detection fails, just need to find out where.

**Comment by lars18th** [comment] 2015-07-10 09:48
Hi Catalin,

My suggestion: Include a parametrer indicating the number of consecutive SI tables for trigger a request to the Oscam server. Why this? Think that you receive a PMT table with "correct" CRC, but next is invalid... if you receive "two" consecutive valid tables, you can assume that both are correct. The problem is that the CRC is not infalible! With very poor signal, sometimes CRC is OK, but not the table. Then you can constrain to read "two", or "three" times before schedule the task.

In any case. This issue is related to "low signal" and "erroneous data". The issue #103 (in my current case) is related to a different thing (timout in the Oscam server).

**Comment by catalinii** [comment] 2015-07-11 02:37
Thank you that helps,

but a stacktrace (from gdb if not generated by minisatip) of the crash can really help (except the log).

**Comment by catalinii** [comment] 2015-10-10 13:27
As it did not occur lately I will close this.

**Closed by catalinii** 2015-10-10 13:27 UTC
