### ISSUE TITLE
RFE: Possible control stream pids ?!

### ISSUE THREAD

**Issue by akawi** [catalinii/minisatip#273] opened 2016-03-04 20:18 UTC
is it's possible to stop some stream pids from status page ?

and possible each stream client conntected ( ip:port agentuser) to be in same line STREAM PIDS and have his info crypty ?

so the page status will have more tools for control

**Comment by catalinii** [comment] 2016-03-07 01:33
To stop specific stream pids is not recommended but probably there is not much work in allowing change for specific variables or call specific functions like killing a stream or an adapter

**Comment by lars18th** [comment] 2016-03-14 09:26
Hi,

I suggest, if you like to implement this, to use a simple REST API, like:

```
- http://minisatip:8080/API/stream/1/TEARDOWN
- http://minisatip:8080/API/stream/99/PLAY
- http://minisatip:8080/API/stream/333/SETUP?pids=0,15,16
...
```

As you can see:

- "/stream/1/" is the Stream ID (in this case "1") used in the RTSP response.
- "/TEARDOWN", "/PLAY", /"SETUP" are the same RTSP commands.
- "?pids=" is identical to SAT>IP parameters.

I feel this is simple and powerfull. For instante, you can initiate a connection using the HTTP protocol, and then control it using this REST API (for example, for add or disable pids; change tune, etc).

You agree?

**Comment by catalinii** [comment] 2016-08-31 05:51
Duplicate of #299

**Closed by catalinii** 2016-08-31 05:51 UTC
