### ISSUE TITLE
feature req: lnb share

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#174] opened 2015-10-06 19:54 UTC
what's about to implement Device bonding (also known as LNB sharing)

**Comment by lars18th** [comment] 2015-10-07 07:12
Hi @9000h ,

"LNB Sharing" or "Transponder Sharing"?

You speak about two or more tuners sharing the same LNB? Then using the same H/L,V/H over all tuners but with different frequencies?
To implement this with minimal changes, perhaps a simple parameter for forcing H/L and V/H in each tuner can be an initial solution.

**Comment by hargut** [comment] 2015-10-17 15:42
Would be a very good feature to have this possiblity, since dual tuner cards are available for low budget, and device bonding opens the possibility to connect both tuners to the same LNB cable (with diode-decoupled signal splitter e.g. Axing SVE 2-01, Spaun VBE 2 PD, Kathrein EBC 10).
This would enables more channels to be watched at the same time, i.e. when a recording is running in the background or multiple clients beeing connected/active. Especially for SAT>IP this would make sense.

VDR introduced that feature with 1.7.22 referencing as "bonded" or "bonding". For technical realization details the patch to 1.7.21 could be interesting. A setting "#TNumber connected to #CableNR" will be helpful if for more complex setups.


Best regards,
Harald

**Comment by catalinii** [comment] 2015-10-30 09:06
Hi 9000h,

can you give me more details, or some cards that supports this and some code I can look at ?

Thanks

**Comment by 9000h** [comment] 2015-10-30 11:48
Hi,
as already mentioned VDR has it  since a very long time, but also other projects like.

https://github.com/jannic/getstream
cesbo/astra
...
CU
9000h

**Comment by hargut** [comment] 2015-10-31 07:40
As already mentioned above the integration of this feature to vdr was done in version 1.7.22. Below you can find the patch for 1.7.21 to 1.7.22. The feature is called "bonding" in vdr. Within some other software it's called LNB Sharing.
ftp://ftp.tvdr.de/vdr/Developer/vdr-1.7.21-1.7.22.diff

As older vdr versions did not support this feature, there is also an "external" vdr patch implementing this feature available. The patch was called vdr lnb sharing, and is available here: http://projects.vdr-developer.org/projects/patch-lnbsharing/files

Many thanks for looking into this!

**Comment by catalinii** [comment] 2015-11-03 01:59
Hi,

I had a bit of time to look thru the code, and in my understanding the change would be that one of the cards is going to send diseqc, pol or the band and only one of the master card would send such information. In this way the slave lnb would use the diseqc, pol and band (high, low) of the master lnb.

The physical connection would be 2 DVB cards connected to a splitter (non-diseqc) that goes to the LNB.

Is my understanding correct ?

If yes, what I can do is mark specific LNBs as slave (and have it just tune to a specific frequency) and the satellite configuration needs to be done on from the satip client (as it is done now).

Thanks

**Comment by 9000h** [comment] 2015-11-03 06:12
right, but we should also think of a some other situations where it would make sense to have some kind of priority for each card depending on the resources the card has. As a sample: If the request is dvbs then we should use a card that may has only dvbs or if there are 2 cards for dvbs and one has a hardware CI then we should use the one without the CI first if no pmt is the request.

**Comment by catalinii** [comment] 2015-11-03 23:39
Hi,

we know if a pmt is requested ONLY after you read the PAT. At that point is already too late to decide to switch the adapter....

If you refer to a way of doing this before tuning... then except dvb-s dvb-s2 I don't think there is another way of determining which card to use.

If we talk about opening the encrypted channels with the card with CI that can be resolved from the Client (create a specific network for encrypted channels) which will be assigned to a card (in tvheadend)...

Or I misunderstood the request ?

**Comment by 9000h** [comment] 2015-11-04 08:19
this it's a real complex thing, there are other situations like a mix of cards like:
1 card DVB-S
2 card DVB-S2
3 card DVB-C/T
4 card DVBC2/T2
5 card DVB-T
6 card DVB-T2

if a DVB-T channel is requested it should go to card 5 first and if a DVB-S channel is requested it should go to card 1 first and for a DVB-C channel card 3 should be used first.

If a crypted channel is requested then it goes even more complex as we support the x_pmt parameter (btw. there is a document at DD which explains how this works with the octonet http://support.digital-devices.eu/download_attachment.php?kb_att=22). The octonet also supports a x_ci parameter to specify the the CI interface and the mutidecrypt if the CI supports it.

maybe this is to complex atm and we should focus fist on stabilize 0.5 and get the CI and independent DD CI to work.

**Comment by catalinii** [comment] 2015-11-05 05:05
Yes, this whole discussion for which there is no simple solution.

The good part is that not many ppl have dvb-s only cards.



However this discussion is different that the lnb share feature from the title for which the fix will be implemented in 0.5 by marking adapters as slave (-S) and allow them to set only the frequency of the tuner.

**Comment by 9000h** [comment] 2015-11-05 06:18
nice !

**Comment by catalinii** [comment] 2015-11-08 08:40
BTW you can open a new enhancement about a good way to choose the DVB card based... I think think we can still discuss about this.... and u can write what u think... I think the only requirement is to choose the adapter BEFORE the tuning...

**Comment by 9000h** [comment] 2015-11-09 12:10
will test it thanks

**Comment by lars18th** [comment] 2015-11-17 09:50
Short question: With the last commit is possible to use one old DVB-S tuner (version 1, not -S2) connected to the same wire as "slave" tuner? Will the minisatip use the correct tuner based on DVB-S or DVB-S2 transponders?

**Comment by 9000h** [comment] 2015-11-17 11:28
I suspect it should work

**Comment by hargut** [comment] 2015-11-21 11:14
I tried to test the device bonding today, but the current minisatip fails on my machine. Please find attached some details on the crashes. Sorry for the German parts in the log.

In case more information is required, kindly let me know.

[device-bonding_crash.txt](https://github.com/catalinii/minisatip/files/40796/device-bonding_crash.txt)

Best regards,
Harald

**Comment by hargut** [comment] 2015-11-21 11:22
Some more gdb info from another minisatip run. Maybe it helps to determine the crash reason.

[device-bonding_crash_gdb.txt](https://github.com/catalinii/minisatip/files/40799/device-bonding_crash_gdb.txt)

**Comment by hargut** [comment] 2015-12-20 14:30
I tried it again by with a fresh checkout from today, but any slave mode activated lets minisatip crash directly.

Would be happy if someone can have a look at the above posted files/information.

Many thanks in advance.


Kind regards,
Harald

**Comment by 9000h** [comment] 2015-12-20 22:07
Hi,

had not much time to test, but I also saw the crashes lately and did not get it to work properly.

CU
9000h

**Comment by catalinii** [comment] 2015-12-21 11:10
I could reproduce this... I will fix it in the next commit.

**Comment by 9000h** [comment] 2016-02-12 08:54
can we make the Readme more clear how to use this feature
if the first DVB-S adapter is 4
-S5  adapter 5 is slave the first DVB-S Adapter 4 in the system
-S5-6 adapter 5 and 6 are slaves of the first DVB-S Adapter 4 in the system
-----------
if the first DVB-S adapter is 4
if  the first DVB-S adapter is 4 if -S5 and -S7 are given, does this mean adapter 5 is slave of adapter 4 and adapater 7 is slave of adapter 6?

**Comment by catalinii** [comment] 2016-02-15 00:45
Hi 9000h,

is more simple than that, you do not need to specify the master adapter.

If an adapter is slave it will not control the LNB at all. It will just change the internal frequency to tune to a specific transponder.
I have added few more lines, feel free to let me know if you need something else added.

**Comment by 9000h** [comment] 2016-02-15 08:36
my question was more to better document/log  the relation Master/Slave if there are more than 2 tuners

**Comment by catalinii** [comment] 2016-02-25 00:35
Hi 9000h,

feel free to create a pull request or the text here if you have the text that is needed.

**Closed** 2018-10-18 18:07 UTC
Labels: enhancement
