### ISSUE TITLE
Channels are not opened

### ISSUE THREAD

**Issue by Shporterator** [catalinii/minisatip#437] opened 2018-03-26 11:41 UTC
Despite a steady signal, some transponders are not scanned, if you scan the channels do not open

log tvheadend
2018-03-26 09:54:55.767 subscription: 0002: "HTTP" subscribing to service "NC+ & Orange Polska & Cyfrowy Polsat /12188V/TV Okazje", weight: 100, adapter: "SAT>IP DVB-S Tuner #1 (192.168.0.104)", network: "NC+ & Orange Polska & Cyfrowy Polsat ", mux: "12188V", provider: "Cyfrowy Polsat S.A", profile="pass", hostname="192.168.0.105", client="VLC/2.2.8 LibVLC/2.2.8"
**2018-03-26 09:54:56.392 satip: SAT>IP DVB-S Tuner #1 (192.168.0.104) - RTSP cmd error 7 (Unknown error -7) [8-404]**

**Comment by catalinii** [comment] 2018-03-26 15:34
Hi,

Can you upload minisatip logs?

Thanks

**Comment by Shporterator** [comment] 2018-03-26 16:16
[m.log](https://github.com/catalinii/minisatip/files/1848573/m.log)

**Comment by 9000h** [comment] 2018-03-26 19:52
can you describe your hardware
```
[26/03 11:46:53.254]: opening adapter 0 failed
```

**Comment by Shporterator** [comment] 2018-03-26 19:54
tbs5580

**Comment by Shporterator** [comment] 2018-03-26 19:54
the problem starts with [26/03 12:39:41.692]:

**Comment by 9000h** [comment] 2018-03-26 20:12
it seem to reach MAX_PIDS and may fail there
```
[26/03 12:40:15.201]: MAX_PIDS (64) reached for adapter 1 in adding PID: 7000
```

**Comment by Shporterator** [comment] 2018-03-26 20:16
and how to solve this problem?

**Comment by 9000h** [comment] 2018-03-26 20:24
the only way I see is to switch to FULLMUX_PID (8192) when the PID filter overflows

**Comment by Shporterator** [comment] 2018-03-26 20:25
how to do it? I use tvheadend

**Comment by 9000h** [comment] 2018-03-26 20:33
thv should do it already 
https://tvheadend.org/projects/tvheadend/repository/revisions/718418b83bdbac76cf3d2373d4b4bb10c6580ce9

**Comment by Shporterator** [comment] 2018-03-26 20:42
I'm using the latest version, but apparently the problem persists.

**Comment by perexg** [comment] 2018-03-27 15:52
The problem is that minisatip subscribes all PMT PIDs (for descrambling?), so you get the 

<pre>
[27/03 15:33:34.898]: Got the new transponder 1CE8 7400, position 0, 129 ms after tune
[27/03 15:33:34.899]: Start streaming for stream 0, len 188 to handle 11 => 192.168.0.104:47534
[27/03 15:33:34.950]: PAT Adapter 1, Transponder ID 7400, len 279, version 50
[27/03 15:33:12.567]: Adapter 1, PMT sid 7304 (1C88), pid 38
[27/03 15:33:12.567]: Adapter 1, PMT sid 7305 (1C89), pid 49
[27/03 15:33:12.568]: Adapter 1, PMT sid 7355 (1CBB), pid 75
[27/03 15:33:12.569]: Adapter 1, PMT sid 7356 (1CBC), pid 66
[27/03 15:33:12.569]: Adapter 1, PMT sid 7380 (1CD4), pid 94
[27/03 15:33:12.570]: Adapter 1, PMT sid 7393 (1CE1), pid 52
[27/03 15:33:12.571]: Adapter 1, PMT sid 7394 (1CE2), pid 53
[27/03 15:33:12.572]: Adapter 1, PMT sid 7395 (1CE3), pid 54
[27/03 15:33:12.572]: Adapter 1, PMT sid 7396 (1CE4), pid 55
[27/03 15:33:12.573]: Adapter 1, PMT sid 7397 (1CE5), pid 56
[27/03 15:33:12.574]: Adapter 1, PMT sid 7398 (1CE6), pid 57
[27/03 15:33:12.575]: Adapter 1, PMT sid 7399 (1CE7), pid 58
[27/03 15:33:12.575]: Adapter 1, PMT sid 7392 (1CE0), pid 59
[27/03 15:33:12.576]: Adapter 1, PMT sid 7384 (1CD8), pid 88
[27/03 15:33:12.577]: Adapter 1, PMT sid 7382 (1CD6), pid 90
[27/03 15:33:12.577]: Adapter 1, PMT sid 7381 (1CD5), pid 91
[27/03 15:33:12.578]: Adapter 1, PMT sid 7385 (1CD9), pid 92
[27/03 15:33:12.579]: Adapter 1, PMT sid 7386 (1CDA), pid 95
[27/03 15:33:12.579]: Adapter 1, PMT sid 7389 (1CDD), pid 98
[27/03 15:33:12.580]: Adapter 1, PMT sid 7390 (1CDE), pid 99
[27/03 15:33:12.581]: Adapter 1, PMT sid 7391 (1CDF), pid 89
[27/03 15:33:12.582]: Adapter 1, PMT sid 7318 (1C96), pid 42
[27/03 15:33:12.582]: Adapter 1, PMT sid 7302 (1C86), pid 35
[27/03 15:33:12.583]: Adapter 1, PMT sid 7303 (1C87), pid 36
[27/03 15:33:12.584]: Adapter 1, PMT sid 7375 (1CCF), pid 48
[27/03 15:33:12.585]: Adapter 1, PMT sid 7301 (1C85), pid 34
[27/03 15:33:12.585]: Adapter 1, PMT sid 7373 (1CCD), pid 47
[27/03 15:33:12.586]: Adapter 1, PMT sid 7307 (1C8B), pid 40
[27/03 15:33:12.587]: Adapter 1, PMT sid 7315 (1C93), pid 41
[27/03 15:33:12.588]: Adapter 1, PMT sid 7316 (1C94), pid 50
[27/03 15:33:12.588]: Adapter 1, PMT sid 7306 (1C8A), pid 39
[27/03 15:33:12.589]: Adapter 1, PMT sid 7308 (1C8C), pid 256
[27/03 15:33:12.590]: Adapter 1, PMT sid 7310 (1C8E), pid 44
[27/03 15:33:12.591]: Adapter 1, PMT sid 7349 (1CB5), pid 43
[27/03 15:33:12.591]: Adapter 1, PMT sid 7351 (1CB7), pid 61
[27/03 15:33:12.592]: Adapter 1, PMT sid 7352 (1CB8), pid 62
[27/03 15:33:12.593]: Adapter 1, PMT sid 7353 (1CB9), pid 63
[27/03 15:33:12.594]: Adapter 1, PMT sid 7358 (1CBE), pid 68
[27/03 15:33:12.594]: Adapter 1, PMT sid 7359 (1CBF), pid 69
[27/03 15:33:12.595]: Adapter 1, PMT sid 7361 (1CC1), pid 71
[27/03 15:33:12.596]: Adapter 1, PMT sid 7362 (1CC2), pid 72
[27/03 15:33:12.597]: Adapter 1, PMT sid 7363 (1CC3), pid 73
[27/03 15:33:12.597]: Adapter 1, PMT sid 7321 (1C99), pid 81
[27/03 15:33:12.598]: Adapter 1, PMT sid 7322 (1C9A), pid 82
[27/03 15:33:12.599]: Adapter 1, PMT sid 7325 (1C9D), pid 85
[27/03 15:33:12.600]: Adapter 1, PMT sid 7326 (1C9E), pid 86
[27/03 15:33:12.600]: Adapter 1, PMT sid 7327 (1C9F), pid 87
[27/03 15:33:12.601]: Adapter 1, PMT sid 7328 (1CA0), pid 188
[27/03 15:33:12.602]: Adapter 1, PMT sid 7320 (1C98), pid 80
[27/03 15:33:12.603]: Adapter 1, PMT sid 7323 (1C9B), pid 83
[27/03 15:33:12.604]: Adapter 1, PMT sid 7324 (1C9C), pid 84
[27/03 15:33:12.605]: Adapter 1, PMT sid 7376 (1CD0), pid 65
[27/03 15:33:12.606]: Adapter 1, PMT sid 7350 (1CB6), pid 70
[27/03 15:33:12.607]: Adapter 1, PMT sid 7365 (1CC5), pid 51
[27/03 15:33:12.608]: Adapter 1, PMT sid 7354 (1CBA), pid 64
[27/03 15:33:12.609]: Adapter 1, PMT sid 7331 (1CA3), pid 7001
[27/03 15:33:12.610]: Adapter 1, PMT sid 7330 (1CA2), pid 7000
[27/03 15:33:12.611]: Adapter 1, PMT sid 7332 (1CA4), pid 7002

..... 

[27/03 15:33:34.963]: MAX_PIDS (64) reached for adapter 1 in adding PID: 7000
</pre>

**Comment by catalinii** [comment] 2018-03-27 16:03
You can disable this behavior by changing opts.pmt_scan = 0 in minisatip.c.

**Comment by perexg** [comment] 2018-03-27 16:14
@catalinii : I don't think that this option should be turned on by default. It really confuses the PMT allocation logic in clients.

@Shporterator : You may also try to increase the PID limit in dvb.h - MAX_PIDS .

**Comment by catalinii** [comment] 2018-03-27 17:29
I will push the MAX_PIDS to 128 in any case in dvb.h in the next commit.

@perexg, the client should not know about what minisatip does (adding more PMT), can you tell me more about what happens on the tvh side when this option is enabled ?

Thanks

**Comment by perexg** [comment] 2018-03-27 17:40
Yes, TVH does also PMT scan, but there's max PID limit set in the adapter settings and TVH does not cross this limit (the scan is split - only allowed count of PIDs is subscribed at the time). Of course, if there's a request for streaming (higher priority) which is beyond the PID filter limit, the full-mux stream is requested.

TVH assumes the configured maximal count of PIDs is available. If you do something hidden in the server (open more PIDs than the client expects) you'll screw the PID management in TVH. Basically, you should not return the error to the client when the internal PID limit is reached (but open the full-mux stream in minisatip instead and do the software filtering).

**Comment by henfri** [comment] 2018-07-29 20:33
Hello,

I have compiled the latest version from git in which MAX_PID is set to 128 already.

Still, I get the error
```
2018-07-29 20:28:01.354 [   INFO] mpegts: 11362H in DVB-S Netzwerk - tuning on SAT>IP DVB-S Tuner #1 (192.168.177.3)
2018-07-29 20:28:01.354 [   INFO] subscription: 0005: "scan" subscribing to mux "11362H", weight: 6, adapter: "SAT>IP DVB-S Tuner #1 (192.168.177.3)", network: "DVB-S Netzwerk", service: "Raw PID Subscription"
2018-07-29 20:28:01.357 [  ERROR] satip: SAT>IP DVB-S Tuner #1 (192.168.177.3) - RTSP cmd error 7 (No error information) [8-404]
2018-07-29 20:28:11.354 [   INFO] mpegts: 11362H in DVB-S Netzwerk - scan no data, failed
2018-07-29 20:28:11.354 [   INFO] subscription: 0005: "scan" unsubscribing
```

Shouldn't this problem be fixed now?

Is there anything else, I need to do in order to use minisatip as source of tvheadend?

Regards,
Hendrik

**Comment by catalinii** [comment] 2018-07-29 20:42
Hi, can you upload minisatip log ?

Thanks

**Comment by henfri** [comment] 2018-07-29 20:53
Hello,

thanks for your quick reply.
I fear the log is not verbose enough:
```
Jul 29 22:50:42 homeserver systemd[1]: Starting Multi-threaded SAT>IP server...
Jul 29 22:50:52 homeserver systemd[1]: Started Multi-threaded SAT>IP server.
Jul 29 22:50:52 homeserver minisatip[17849]: [29/07 22:50:52.484 main]: Initializing with 4 devices
Jul 29 22:50:52 homeserver minisatip[17849]: [29/07 22:50:52.870 main]: tuning to 11641000(1891000) pol: h (2) sr:22000000 fec:56 delsys:dvb
Jul 29 22:50:53 homeserver minisatip[17849]: [29/07 22:50:53.114 main]: tuning to 11493000(1743000) pol: h (2) sr:22000000 fec:23 delsys:dvb
Jul 29 22:50:53 homeserver minisatip[17849]: [29/07 22:50:53.370 main]: tuning to 11582000(1832000) pol: h (2) sr:22000000 fec:23 delsys:dvb
Jul 29 22:50:56 homeserver minisatip[17849]: [29/07 22:50:56.058 main]: tuning to 11836000(1236000) pol: h (2) sr:27500000 fec:34 delsys:dvb
Jul 29 22:50:59 homeserver minisatip[17849]: [29/07 22:50:59.738 main]: tuning to 11836000(1236000) pol: h (2) sr:27500000 fec:34 delsys:dvb
Jul 29 22:51:00 homeserver minisatip[17849]: [29/07 22:51:00.238 main]: tuning to 12109000(1509000) pol: h (2) sr:27500000 fec:34 delsys:dvb
Jul 29 22:51:00 homeserver minisatip[17849]: [29/07 22:51:00.890 main]: tuning to 12187000(1587000) pol: h (2) sr:27500000 fec:34 delsys:dvb
Jul 29 22:51:03 homeserver minisatip[17849]: [29/07 22:51:03.266 main]: tuning to 11954000(1354000) pol: h (2) sr:27500000 fec:34 delsys:dvb
Jul 29 22:51:21 homeserver minisatip[17849]: [29/07 22:51:21.590 main]: tuning to 12265000(1665000) pol: h (2) sr:27500000 fec:34 delsys:dvb
Jul 29 22:51:21 homeserver minisatip[17849]: [29/07 22:51:21.622 main]: tuning to 12421000(1821000) pol: h (2) sr:27500000 fec:34 delsys:dvb
Jul 29 22:51:21 homeserver minisatip[17849]: [29/07 22:51:21.873 main]: tuning to 12460000(1860000) pol: h (2) sr:27500000 fec:34 delsys:dvb

```

Would 
-d http,pmt

help?

Regards,
Hendrik

**Comment by catalinii** [comment] 2018-07-29 21:02
yes, try
 -l http,pmt

**Comment by henfri** [comment] 2018-07-30 17:16
Hello,

I got a bit further, but this seems a bit more complex...
(TL;DR: In the end I was able to reproduce. Maybe start with the end)

**First**, I did run
`./minisatip -f -x 8081 -p http://homeserver:8081/playlist.m3u -d http,pmt`
which did not give any new output when I initiated a scan in tvheadend.

**Then** I ran 
`./minisatip -f -l http,pmt -x 8081 -p http://homeserver:8081/playlist.m3u`
I got lots of output even before running a scan. But the content did indicate, that my VDR with SatIP Plugin was causing this. So, I stopped VDR and ran the same command again and initiated a Scan in TVheadend. This worked (!!) The minisatip.log is here https://gist.github.com/henfri/5ab08426092b9021a8bc7f5118d54380

TVHeadend reported

> 2018-07-30 16:54:42.785 [   INFO] mpegts: 11552.75H in DVB-S Netzwerk scan complete
> 2018-07-30 16:54:42.785 [   INFO] subscription: 0057: "scan" unsubscribing
> 2018-07-30 16:54:42.786 [   INFO] mpegts: 11611.75H in DVB-S Netzwerk - tuning on SAT>IP DVB-S Tuner #2 (192.168.177.3)
> 2018-07-30 16:54:42.786 [   INFO] epggrab: 11611.75H in DVB-S Netzwerk - registering mux for OTA EPG
> 2018-07-30 16:54:42.786 [   INFO] subscription: 005C: "scan" subscribing to mux "11611.75H", weight: 6, adapter: "SAT>IP DVB-S Tuner #2 (192.168.177.3)", network: "DVB-S Netzwerk", service: "Raw PID Subscription"
> 2018-07-30 16:54:52.299 [   INFO] mpegts: 11582.25H in DVB-S Netzwerk - scan no data, failed
> 2018-07-30 16:54:52.299 [   INFO] subscription: 005A: "scan" unsubscribing
> 2018-07-30 16:54:52.299 [   INFO] mpegts: 11670.75H in DVB-S Netzwerk - tuning on SAT>IP DVB-S Tuner #1 (192.168.177.3)
> 2018-07-30 16:54:52.299 [   INFO] epggrab: 11670.75H in DVB-S Netzwerk - registering mux for OTA EPG
> 2018-07-30 16:54:52.302 [   INFO] subscription: 005F: "scan" subscribing to mux "11670.75H", weight: 6, adapter: "SAT>IP DVB-S Tuner #1 (192.168.177.3)", network: "DVB-S Netzwerk", service: "Raw PID Subscription"

Now I wanted to reproduce the original problem by starting VDR again. But the problem did not re-appear. Instead I got:
```
2018-07-30 17:07:42.558 [  ERROR] satip: SAT>IP DVB-S Tuner #2 (192.168.177.3) - failed to tune (-111)
2018-07-30 17:08:13.345 [   INFO] subscription: 01DD: "epggrab" unsubscribing
2018-07-30 17:08:14.345 [   INFO] mpegts: 11111.75H in DVB-S Netzwerk - tuning on SAT>IP DVB-S Tuner #1 (192.168.177.3)
2018-07-30 17:08:14.345 [   INFO] subscription: 01E1: "epggrab" subscribing to mux "11111.75H", weight: 4, adapter: "SAT>IP DVB-S Tuner #1 (192.168.177.3)", network: "DVB-S Netzwerk", service: "Raw PID Subscription"
2018-07-30 17:08:22.557 [   INFO] subscription: 01DF: "epggrab" unsubscribing
2018-07-30 17:08:23.557 [   INFO] mpegts: 10964.25H in DVB-S Netzwerk - tuning on SAT>IP DVB-S Tuner #2 (192.168.177.3)
2018-07-30 17:08:23.557 [   INFO] subscription: 01E3: "epggrab" subscribing to mux "10964.25H", weight: 4, adapter: "SAT>IP DVB-S Tuner #2 (192.168.177.3)", network: "DVB-S Netzwerk", service: "Raw PID Subscription"
2018-07-30 17:08:23.558 [  ERROR] satip: SAT>IP DVB-S Tuner #2 (192.168.177.3) - failed to tune (-111)
2018-07-30 17:08:54.345 [   INFO] subscription: 01E1: "epggrab" unsubscribing
2018-07-30 17:08:55.345 [   INFO] mpegts: 10920.75H in DVB-S Netzwerk - tuning on SAT>IP DVB-S Tuner #1 (192.168.177.3)
2018-07-30 17:08:55.345 [   INFO] subscription: 01E5: "epggrab" subscribing to mux "10920.75H", weight: 4, adapter: "SAT>IP DVB-S Tuner #1 (192.168.177.3)", network: "DVB-S Netzwerk", service: "Raw PID Subscription"
```

**Then** I startet to write this post. 
For some reason I startet minisatip again and now, the original error is back (while VDR is still running). 
The log of this is here https://gist.github.com/henfri/75cff28eaf9bac1f1b21729dbf9bfaf1

So, I have the impression that this could be related to tvheadend and vdr fighting for the satip-devices. Is that right?
I am surprised by that though, as I have four tuners, and only two are available to TVheadend. But in fact four are available to VDR. I just did not expect VDR to use all four at the same time while idling. Also I would expect a more clear output from minisatip and tvheadend.



Greetings,
Hendrik

**Comment by henfri** [comment] 2018-07-30 17:17
Hello,

I got a bit further, but this seems a bit more complex...
(TL;DR: In the end I was able to reproduce. Maybe start with the end)

**First**, I did run
`./minisatip -f -x 8081 -p http://homeserver:8081/playlist.m3u -d http,pmt`
which did not give any new output when I initiated a scan in tvheadend.

**Then** I ran 
`./minisatip -f -l http,pmt -x 8081 -p http://homeserver:8081/playlist.m3u`
I got lots of output even before running a scan. But the content did indicate, that my VDR with SatIP Plugin was causing this. So, I stopped VDR and ran the same command again and initiated a Scan in TVheadend. This worked (!!) The minisatip.log is here https://gist.github.com/henfri/5ab08426092b9021a8bc7f5118d54380

TVHeadend reported

> 2018-07-30 16:54:42.785 [   INFO] mpegts: 11552.75H in DVB-S Netzwerk scan complete
> 2018-07-30 16:54:42.785 [   INFO] subscription: 0057: "scan" unsubscribing
> 2018-07-30 16:54:42.786 [   INFO] mpegts: 11611.75H in DVB-S Netzwerk - tuning on SAT>IP DVB-S Tuner #2 (192.168.177.3)
> 2018-07-30 16:54:42.786 [   INFO] epggrab: 11611.75H in DVB-S Netzwerk - registering mux for OTA EPG
> 2018-07-30 16:54:42.786 [   INFO] subscription: 005C: "scan" subscribing to mux "11611.75H", weight: 6, adapter: "SAT>IP DVB-S Tuner #2 (192.168.177.3)", network: "DVB-S Netzwerk", service: "Raw PID Subscription"
> 2018-07-30 16:54:52.299 [   INFO] mpegts: 11582.25H in DVB-S Netzwerk - scan no data, failed
> 2018-07-30 16:54:52.299 [   INFO] subscription: 005A: "scan" unsubscribing
> 2018-07-30 16:54:52.299 [   INFO] mpegts: 11670.75H in DVB-S Netzwerk - tuning on SAT>IP DVB-S Tuner #1 (192.168.177.3)
> 2018-07-30 16:54:52.299 [   INFO] epggrab: 11670.75H in DVB-S Netzwerk - registering mux for OTA EPG
> 2018-07-30 16:54:52.302 [   INFO] subscription: 005F: "scan" subscribing to mux "11670.75H", weight: 6, adapter: "SAT>IP DVB-S Tuner #1 (192.168.177.3)", network: "DVB-S Netzwerk", service: "Raw PID Subscription"

Now I wanted to reproduce the original problem by starting VDR again. But the problem did not re-appear. Instead I got:
```
2018-07-30 17:07:42.558 [  ERROR] satip: SAT>IP DVB-S Tuner #2 (192.168.177.3) - failed to tune (-111)
2018-07-30 17:08:13.345 [   INFO] subscription: 01DD: "epggrab" unsubscribing
2018-07-30 17:08:14.345 [   INFO] mpegts: 11111.75H in DVB-S Netzwerk - tuning on SAT>IP DVB-S Tuner #1 (192.168.177.3)
2018-07-30 17:08:14.345 [   INFO] subscription: 01E1: "epggrab" subscribing to mux "11111.75H", weight: 4, adapter: "SAT>IP DVB-S Tuner #1 (192.168.177.3)", network: "DVB-S Netzwerk", service: "Raw PID Subscription"
2018-07-30 17:08:22.557 [   INFO] subscription: 01DF: "epggrab" unsubscribing
2018-07-30 17:08:23.557 [   INFO] mpegts: 10964.25H in DVB-S Netzwerk - tuning on SAT>IP DVB-S Tuner #2 (192.168.177.3)
2018-07-30 17:08:23.557 [   INFO] subscription: 01E3: "epggrab" subscribing to mux "10964.25H", weight: 4, adapter: "SAT>IP DVB-S Tuner #2 (192.168.177.3)", network: "DVB-S Netzwerk", service: "Raw PID Subscription"
2018-07-30 17:08:23.558 [  ERROR] satip: SAT>IP DVB-S Tuner #2 (192.168.177.3) - failed to tune (-111)
2018-07-30 17:08:54.345 [   INFO] subscription: 01E1: "epggrab" unsubscribing
2018-07-30 17:08:55.345 [   INFO] mpegts: 10920.75H in DVB-S Netzwerk - tuning on SAT>IP DVB-S Tuner #1 (192.168.177.3)
2018-07-30 17:08:55.345 [   INFO] subscription: 01E5: "epggrab" subscribing to mux "10920.75H", weight: 4, adapter: "SAT>IP DVB-S Tuner #1 (192.168.177.3)", network: "DVB-S Netzwerk", service: "Raw PID Subscription"
```

**Then** I startet to write this post. 
For some reason I startet minisatip again and now, the original error is back (while VDR is still running). 
The log of this is here https://gist.github.com/henfri/75cff28eaf9bac1f1b21729dbf9bfaf1

So, I have the impression that this could be related to tvheadend and vdr fighting for the satip-devices. Is that right?
I am surprised by that though, as I have four tuners, and only two are available to TVheadend. But in fact four are available to VDR. I just did not expect VDR to use all four at the same time while idling. Also I would expect a more clear output from minisatip and tvheadend.



Greetings,
Hendrik

**Comment by henfri** [comment] 2018-07-30 17:18
Hello,

I got a bit further, but this seems a bit more complex...
(TL;DR: In the end I was able to reproduce. Maybe start with the end)

**First**, I did run
`./minisatip -f -x 8081 -p http://homeserver:8081/playlist.m3u -d http,pmt`
which did not give any new output when I initiated a scan in tvheadend.

**Then** I ran 
`./minisatip -f -l http,pmt -x 8081 -p http://homeserver:8081/playlist.m3u`
I got lots of output even before running a scan. But the content did indicate, that my VDR with SatIP Plugin was causing this. So, I stopped VDR and ran the same command again and initiated a Scan in TVheadend. This worked (!!) The minisatip.log is here https://gist.github.com/henfri/5ab08426092b9021a8bc7f5118d54380

TVHeadend reported

> 2018-07-30 16:54:42.785 [   INFO] mpegts: 11552.75H in DVB-S Netzwerk scan complete
> 2018-07-30 16:54:42.785 [   INFO] subscription: 0057: "scan" unsubscribing
> 2018-07-30 16:54:42.786 [   INFO] mpegts: 11611.75H in DVB-S Netzwerk - tuning on SAT>IP DVB-S Tuner #2 (192.168.177.3)
> 2018-07-30 16:54:42.786 [   INFO] epggrab: 11611.75H in DVB-S Netzwerk - registering mux for OTA EPG
> 2018-07-30 16:54:42.786 [   INFO] subscription: 005C: "scan" subscribing to mux "11611.75H", weight: 6, adapter: "SAT>IP DVB-S Tuner #2 (192.168.177.3)", network: "DVB-S Netzwerk", service: "Raw PID Subscription"
> 2018-07-30 16:54:52.299 [   INFO] mpegts: 11582.25H in DVB-S Netzwerk - scan no data, failed
> 2018-07-30 16:54:52.299 [   INFO] subscription: 005A: "scan" unsubscribing
> 2018-07-30 16:54:52.299 [   INFO] mpegts: 11670.75H in DVB-S Netzwerk - tuning on SAT>IP DVB-S Tuner #1 (192.168.177.3)
> 2018-07-30 16:54:52.299 [   INFO] epggrab: 11670.75H in DVB-S Netzwerk - registering mux for OTA EPG
> 2018-07-30 16:54:52.302 [   INFO] subscription: 005F: "scan" subscribing to mux "11670.75H", weight: 6, adapter: "SAT>IP DVB-S Tuner #1 (192.168.177.3)", network: "DVB-S Netzwerk", service: "Raw PID Subscription"

Now I wanted to reproduce the original problem by starting VDR again. But the problem did not re-appear. Instead I got:
```
2018-07-30 17:07:42.558 [  ERROR] satip: SAT>IP DVB-S Tuner #2 (192.168.177.3) - failed to tune (-111)
2018-07-30 17:08:13.345 [   INFO] subscription: 01DD: "epggrab" unsubscribing
2018-07-30 17:08:14.345 [   INFO] mpegts: 11111.75H in DVB-S Netzwerk - tuning on SAT>IP DVB-S Tuner #1 (192.168.177.3)
2018-07-30 17:08:14.345 [   INFO] subscription: 01E1: "epggrab" subscribing to mux "11111.75H", weight: 4, adapter: "SAT>IP DVB-S Tuner #1 (192.168.177.3)", network: "DVB-S Netzwerk", service: "Raw PID Subscription"
2018-07-30 17:08:22.557 [   INFO] subscription: 01DF: "epggrab" unsubscribing
2018-07-30 17:08:23.557 [   INFO] mpegts: 10964.25H in DVB-S Netzwerk - tuning on SAT>IP DVB-S Tuner #2 (192.168.177.3)
2018-07-30 17:08:23.557 [   INFO] subscription: 01E3: "epggrab" subscribing to mux "10964.25H", weight: 4, adapter: "SAT>IP DVB-S Tuner #2 (192.168.177.3)", network: "DVB-S Netzwerk", service: "Raw PID Subscription"
2018-07-30 17:08:23.558 [  ERROR] satip: SAT>IP DVB-S Tuner #2 (192.168.177.3) - failed to tune (-111)
2018-07-30 17:08:54.345 [   INFO] subscription: 01E1: "epggrab" unsubscribing
2018-07-30 17:08:55.345 [   INFO] mpegts: 10920.75H in DVB-S Netzwerk - tuning on SAT>IP DVB-S Tuner #1 (192.168.177.3)
2018-07-30 17:08:55.345 [   INFO] subscription: 01E5: "epggrab" subscribing to mux "10920.75H", weight: 4, adapter: "SAT>IP DVB-S Tuner #1 (192.168.177.3)", network: "DVB-S Netzwerk", service: "Raw PID Subscription"
```

**Then** I startet to write this post. 
For some reason I startet minisatip again and now, the original error is back (while VDR is still running). 
The log of this is here https://gist.github.com/henfri/75cff28eaf9bac1f1b21729dbf9bfaf1

So, I have the impression that this could be related to tvheadend and vdr fighting for the satip-devices. Is that right?
I am surprised by that though, as I have four tuners, and only two are available to TVheadend. But in fact four are available to VDR. I just did not expect VDR to use all four at the same time while idling. Also I would expect a more clear output from minisatip and tvheadend.



Greetings,
Hendrik

**Comment by catalinii** [comment] 2018-08-01 04:52
Hi Hendrik,

Yes both tvheadend and vdr are fighting for resources but both behave a bit differently.
tvh will ask specifically in this case for adapter 1 and 2, while VDR will not specify which adapter it wants. If VDR gets the first or second adapter, TVH will not be able to use it and return an error. If tvh uses 1 or 2, then vdr will get adapter 3, so they will both work. 
In the log you are pasting here, the error is -111 which means that most likely minisatip was down (stopped) when that error appeared.

I am not sure if there is a way to specify in VDR plugin satip whcih adapter to use (I did not check recently). The option to use would be "fe=X" where X is adapter number

Thanks

**Comment by perexg** [comment] 2018-09-25 09:51
Another way is to disable first two tuners in tvheadend (enable tuners 3 and 4). With this setup, the first two tuners will be availabe for clients which does not use fe= parameter (auto tuner assignment).

**Comment by Jalle19** [comment] 2022-02-11 09:06
Closing due to inactivity. If `pmt_scan` default should be changed let's make a separate issue for that.

**Closed by Jalle19** 2022-02-11 09:06 UTC
