### ISSUE TITLE
DVB-C/S FBC Tuner multiple tuning

### ISSUE THREAD

**Issue by SeyedGH** [catalinii/minisatip#400] opened 2017-11-29 03:23 UTC
After 3 days of testing with minisatip and tvheadend with VLC and Kodi, and other boxes,
I can certainly say dual tuning on FBC tuner is not working properly.

(btw I tried to make a forum account but do not get an activation mail)

full logfile when starting second stream [minisatip.zip](https://github.com/catalinii/minisatip/files/1512430/minisatip.zip)

**Comment by catalinii** [comment] 2017-11-30 05:27
Hi,

could you please provide more details about what is not working properly
and what should I look for in the logs ?

Thank you

**Comment by SeyedGH** [comment] 2017-11-30 09:52
Hi there,

As long I am using one tuner at a time it works perfect.
But as soon a second tuner wants to stream the data to a client everything gets messy, mostly I just don't see anything on the second stream, but also i see that first stream is getting choppy every 3 or 5 seconds. I also see then a CC bar on the first stream tuner that is playing with mostly between 2 or 5.

But i tested that is about streaming and not finding the transponder, for example if turn on all the tuners of the DVB-C it can search on all the tuners simultaneously, and it works like a charm.
I also have to mention that playing a second stream on the same adapter in the same transponder works.

So in the log from the point where `PLAY rtsp://192.168.20.30/stream=2` with adapter 2 and sid 1 comes to play that is where the problem begins.

But if you want any log that are more specific I can provide them for you.

**Comment by SeyedGH** [comment] 2017-12-02 13:17
After some investigation of my log files I found out the the stream 2 is send less frequent, see shortened log.
I made sure that multi threading was ON with option -T, apparently it is DISABLED by default.
But still the same problem, but somehow I think it is still running on single thread.
How can i check it is running multi threaded? I am running this one a Vu+ Ultimo 4K with the ARM version.

> L311369: [..:54.362]: send_rtp: s 7896 b S 0, seq 1619 => ..186:57312
L311372: [..:54.362]: send_rtp: s 7896 b S 0, seq 1620 => ..186:57312
L311375: [..:54.362]: send_rtp: s 7896 b S 0, seq 1621 => ..186:57312
L311378: [..:54.362]: send_rtp: s 5640 b S 0, seq 1622 => ..186:57312
L313121: [..:54.410]: send_rtp: s 7896 b S 0, seq 1623 => ..186:57312
L313124: [..:54.410]: send_rtp: s 7896 b S 0, seq 1624 => ..186:57312
L313127: [..:54.411]: send_rtp: s 7896 b S 0, seq 1625 => ..186:57312
L313130: [..:54.411]: send_rtp: s 7896 b S 0, seq 1626 => ..186:57312
L313133: [..:54.411]: send_rtp: s 7896 b S 0, seq 1627 => ..186:57312
L313136: [..:54.411]: send_rtp: s 7708 b S 0, seq 1628 => ..186:57312
L313931: [..:54.431]: send_rtp: s 7896 b S 0, seq 1629 => ..186:57312
L313934: [..:54.431]: send_rtp: s 7896 b S 0, seq 1630 => ..186:57312
L313937: [..:54.431]: send_rtp: s 7896 b S 0, seq 1631 => ..186:57312
L313940: [..:54.431]: send_rtp: s 7896 b S 0, seq 1632 => ..186:57312
L313943: [..:54.432]: send_rtp: s 7896 b S 0, seq 1633 => ..186:57312
L313946: [..:54.432]: send_rtp: s 5828 b S 0, seq 1634 => ..186:57312
L314164: [..:54.435]: send_rtp: s 7144 b **S 1**, seq 102  => ..186:57314
L315038: [..:54.455]: send_rtp: s 7896 b S 0, seq 1635 => ..186:57312
L315041: [..:54.456]: send_rtp: s 7896 b S 0, seq 1636 => ..186:57312
L315044: [..:54.456]: send_rtp: s 7896 b S 0, seq 1637 => ..186:57312
L315047: [..:54.456]: send_rtp: s 7896 b S 0, seq 1638 => ..186:57312
L315050: [..:54.456]: send_rtp: s 7896 b S 0, seq 1639 => ..186:57312
L315053: [..:54.456]: send_rtp: s 6016 b S 0, seq 1640 => ..186:57312
L316077: [..:54.479]: send_rtp: s 7896 b S 0, seq 1641 => ..186:57312
L316080: [..:54.479]: send_rtp: s 7896 b S 0, seq 1642 => ..186:57312
L316083: [..:54.479]: send_rtp: s 7896 b S 0, seq 1643 => ..186:57312
L316086: [..:54.479]: send_rtp: s 7896 b S 0, seq 1644 => ..186:57312
L316089: [..:54.479]: send_rtp: s 7896 b S 0, seq 1645 => ..186:57312
L316092: [..:54.480]: send_rtp: s 6392 b S 0, seq 1646 => ..186:57312
L317219: [..:54.503]: send_rtp: s 7896 b S 0, seq 1647 => ..186:57312
L317222: [..:54.503]: send_rtp: s 7896 b S 0, seq 1648 => ..186:57312
L317225: [..:54.503]: send_rtp: s 7896 b S 0, seq 1649 => ..186:57312
L317228: [..:54.503]: send_rtp: s 7896 b S 0, seq 1650 => ..186:57312
L317231: [..:54.503]: send_rtp: s 7896 b S 0, seq 1651 => ..186:57312
L317234: [..:54.503]: send_rtp: s 6768 b S 0, seq 1652 => ..186:57312
L317462: [..:54.507]: send_rtp: s 5076 b **S 1**, seq 103  => ..186:57314
L319856: [..:54.541]: send_rtp: s 7896 b S 0, seq 1653 => ..186:57312
L319859: [..:54.542]: send_rtp: s 7896 b S 0, seq 1654 => ..186:57312
L319862: [..:54.542]: send_rtp: s 7896 b S 0, seq 1655 => ..186:57312
L319865: [..:54.542]: send_rtp: s 7896 b S 0, seq 1656 => ..186:57312
L319868: [..:54.542]: send_rtp: s 2632 b S 0, seq 1657 => ..186:57312
L320648: [..:54.564]: send_rtp: s 7896 b **S 1**, seq 104  => ..186:57314<

**Comment by catalinii** [comment] 2017-12-02 14:08
Hi if you see 
P

**Comment by catalinii** [comment] 2017-12-02 14:23
Btw, on the frequencies that you are playing do you have signal issues?

**Comment by SeyedGH** [comment] 2017-12-02 14:44
Hmm After I set -T i still do not see AD0
Both of the streams where HD, both of the stream have almost the same amount of bit rate .

The signal is 100% /97% it sais on the HTML. 
![signal](https://user-images.githubusercontent.com/8275308/33516709-8c7b0c7c-d777-11e7-9f67-89d2a45d242e.png)
And that is with every channel.

**Comment by SeyedGH** [comment] 2017-12-02 14:51
And this is what it looks like when two streams are trying.
First one keeps playing right now, and and the second gets nothing.
![signal2](https://user-images.githubusercontent.com/8275308/33516775-ac00ca9a-d778-11e7-8a58-9ee07b269302.png)

**Comment by SeyedGH** [comment] 2017-12-02 14:58
BTW this is my starting string, maybe I am forgetting something??

> ./usr/bin/minisatip/minisatip -f -l -T -e 0-15 -R /usr/bin/minisatip/html

**Comment by SeyedGH** [comment] 2017-12-02 23:50
I saw on the forum there was one person also with a Ultimo 4K but he was able to get multiple streams, but only with errors but that was in end of july, do you have the older version of compiled ARM binaries.
[https://minisatip.org/forum/viewtopic.php?f=5&t=421&start=10](url)
So we can trace back what commit is causing this??
I am willing to give you a donation if we will get this up and running.

**Comment by catalinii** [comment] 2017-12-03 02:39
Hi,

I am interested also in making this work, but only this month (at the end) I will be able to install my own FBC receiver so I can test more. My version is a DVB-S2.

Currently, the CC on some pids is expected and will not cause image break-ups, but what you are explaining (one tuner to work and the other one to not work) is not really expected.

The previous versions had issues with low bit rate pids (for example if you want just PAT, PMT, EPG) but it would work if you want to play an SD and HD channel. The new functionality added in the recent commits affects just low bit rate pids ( pids < 32 . and PMT Pids).

But basically the most important thing is to make sure you do have signal when playing the channels. You can use VLC to play and use fe=XX&freq=... to select the adapter you want and see if the channels works on one adapter and does not work on another one.

Thank you

**Comment by SeyedGH** [comment] 2017-12-03 11:48
Yesterday night I thought i am going to be wise, and i did the following.

`./usr/bin/minisatip/minisatip -e 0 -R /usr/bin/minisatip/html -y 554 -x 8080 -m 001122334455
./usr/bin/minisatip/minisatip -e 1 -R /usr/bin/minisatip/html -y 555 -x 8081 -m 001122334466`

And guess what, they have exactly the same problem, if play on one the other one wont work, and vice versa.
So i think this could have something to do with FBC drivers, and how they react.

I did some digging, and these are the changes in Ultimo 4k drivers from may 2017 on onward.

> 22 May 2017
>update drivers(duo2, solo2, solose, zero, solo4k, uno4k, ultimo4k)
>- Fix DVB-T2 tuning problem(TT2L08)
>- Support DVB-CI in vtuner
>- Support scrambled playback(solo4k, uno4k, ultimo4k : E2 update will follow)
>- Support Bluetooth(solo4k, uno4k : Needs USB Vu+ BT)
>- Fix Misc.

> 21 August 2017
>update drivers(solo4k, uno4k, ultimo4k)
>- Support Quad PiP(E2 update is necessary. In Solo4K, 4th pip is I frame decoder) <<<<< :)
>- Fix recording problem when there are many audio channels
>- Fix screen capture(grab)

>31 August 2017
>update drivers(solo4k, uno4k, ultimo4k)
>- Fix grab when not tuned.
>- Change nim_sockets information to disable FCC in usbtuners

>30 Oct 2017
>update drivers(solo4k, uno4k, ultimo4k, uno, ultimo)
>- Support vtuner and channel stream in QuadPiP(solo4k, uno4k, ultimo4k)
>- Support TT2L08(uno, ultimo)
>- Improve demux
>- Fix misc.

>1 Nov 2017
>update drivers(solo4k, uno4k, ultimo4k)
>- Revert: Turn off loudness equivalence(solo4k, uno4k, ultimo4k)
>- Add proc entries to support Amazon service

>20 Nov 2017
>update dirvers(solo4k, uno4k, uno4kse, ultimo4k)
>- Improve demux
>- Improve DVB-CI
>- Fix problem when reading some proc entries
>- Fix misc

>22 Nov 2017
>update driver(ultimo4k)
>- Fix WOWL problem

[https://vuplus-images.co.uk/index.php?threads/latest-drivers-for-vu.5953/](url)

Maybe something pops in to your mind what causes the issue.

**Comment by estimadarocha** [comment] 2017-12-03 12:34
@SeyedGH did you try running minisatip on images with different drivers to see if there's any difference? I have my uno 4k disconnected right now but last time I used it if I remember right I was able to get more than one stream from it... my problem was the CC errors. I am using DVB-C.

**Comment by SeyedGH** [comment] 2017-12-03 12:39
I am on OpenATV 6.1 right now, I was searching for my backup USB with the older models but cant't find them right now, that was also my guess running it on an older older version, but i could try a different image brand as well, any suggestions ?

**Comment by estimadarocha** [comment] 2017-12-03 12:53
I can have a look on the dare of my image... but mine is probably six months ot even older. You have a lot of teams you can try all of them have old images so probably also old drivers. I guess I have to turn mine again to help on the tests. 

I am also sure catalinii will solve this as soon as he gets his hands on his stb with fbc.

**Comment by SeyedGH** [comment] 2017-12-03 15:17
Ok Update.
Found an image of VTI from beginning of Ultimo 4k. 12/2016.
Did not update it, put minisatip on it with WINSCP made it executable.
logged in with putty.
`Init 4`
`./usr/bin/minisatip/minisatip -f -l html -R /usr/bin/minisatip/html`
conclusion the same.
Can watch every channel, except two or more at once.
And where are talking about SD unencrypted DVB-C channels.

On top of that, I tried the following:
Took my DVB-S card out of the ultimo 4k I though maybe two cards are the problem.
Exchanged my Zyxel GS1920 switch for the most simple gigabit switch.

**Comment by estimadarocha** [comment] 2017-12-03 15:33
Let me get home and turn it on and I will see if I have any old one.... indeed for me the old ones arent useful because i can't scan and grab epg on low data pids. Catalinii did make a wonderful job in this new code but since it's new maybe some bugs there... there's where we can help
.. making some debug if he needs. 

If you need something from me just ask

**Comment by SeyedGH** [comment] 2017-12-03 16:37
For bug tracking purposes it is best to have a set of logs with working conditions and one set with the bug.
So we understand what we are looking for.

**Comment by SeyedGH** [comment] 2017-12-03 17:27
@catalinii, could it be that commit 614c2a85c9174ea48abb61306eccc588ac0e7f6e,  causing the issue, that FBC tuners don't like this when streaming multiple streams?

**Comment by SeyedGH** [comment] 2017-12-03 23:53
More digging on the log.

As it turns out from the moment en start playing stream 2 there are a lot of `pid 4701 not found` to exact around the 26k times I think this is causing the stream not getting trough. 
But playing the same channel as the first stream does get played with the same pids.
So...

Somewhere here..
```
SPid *find_pid(int aid, int p)
{
	int i;
	adapter *ad = get_adapter(aid);

	if (!ad)
		return NULL;

	for (i = 0; i < MAX_PIDS; i++)
		if ((ad->pids[i].flags > 0) && (ad->pids[i].pid == p))
			return &ad->pids[i];
	return NULL;
}
```
but the question remains why, the MAX_PID should not be a problem the total count of pids is only 7 and MAX_PIDS is defined to 64,  so it should come to this line `if ((ad->pids[i].flags > 0) && (ad->pids[i].pid == p))` one checking if the pid is there, the other one checking if pid has a flag.

**Comment by SeyedGH** [comment] 2017-12-05 01:38
@catalinii witch compiler are you using for your ARM binary?
Is it stbgcc-4.8-1.7??
I was able to compile a version of the source but it was very choppy but after I installed all the libraries 
I got some trouble letting this compiler understand where my includes are, any suggestions?

**Comment by SeyedGH** [comment] 2017-12-10 12:35
Thus far I have found out that the stream from the second transponder/frontend gets mixed up in the socket of the first transponder/frontend.

**Comment by catalinii** [comment] 2017-12-11 17:49
Can you upload full logs with "sid count= 1, master sid= 0, packet no sid = 217" messages ?

Thank you

**Comment by SeyedGH** [comment] 2017-12-11 20:16
./usr/bin/minisatip/minisatip -v general,http,socketworks,stream,adapter,satipc,pmt,tables,dvbapi,lock,netceiver,dvbca,axe,socket,utils,dmx,ssdp,dvb -R /usr/bin/minisatip/html

[log.zip](https://github.com/catalinii/minisatip/files/1549245/log.zip)

**Comment by SeyedGH** [comment] 2017-12-12 20:19
Was scrolling trough the log and giving in some search in Notepad++ for the fun of it, you never know what you might find!

and i stumbled on this, mutex 0xb5a0cf48 memory allocation get opened in the beginning from adapter AD0 thread it get destroyed a second later, but some time later the same memory allocation is used by AD1 could it be that the kernel does not destroy something the right way and this is why the file descriptors gets messed up?

[11/12 20:22:04.912 AD0]: Mutex init 0xb5a0cf48
[11/12 20:22:04.912 AD0]: utils.c:1474 Locking mutex 0xb5a0cf48
[11/12 20:22:04.912 AD0]: socketworks.c:579 Unlocking mutex 0xb5a0cf48
[11/12 20:22:04.986 AD0]: socketworks.c:465 Locking mutex 0xb5a0cf48
[11/12 20:22:04.988 AD0]: socketworks.c:500 Unlocking mutex 0xb5a0cf48
[11/12 20:22:05.061 AD0]: socketworks.c:465 Locking mutex 0xb5a0cf48
[11/12 20:22:05.061 AD0]: socketworks.c:500 Unlocking mutex 0xb5a0cf48
[11/12 20:22:05.102 AD0]: socketworks.c:592 Locking mutex 0xb5a0cf48
[11/12 20:22:05.102 AD0]: Destroying mutex 0xb5a0cf48
[11/12 20:22:12.793 main]: Mutex init 0xb5a0cf48
[11/12 20:22:12.793 main]: utils.c:1474 Locking mutex 0xb5a0cf48
[11/12 20:22:12.793 main]: socketworks.c:579 Unlocking mutex 0xb5a0cf48
[11/12 20:22:12.845 AD1]: socketworks.c:465 Locking mutex 0xb5a0cf48
[11/12 20:22:12.846 AD1]: socketworks.c:500 Unlocking mutex 0xb5a0cf48
[11/12 20:22:12.846 AD1]: socketworks.c:465 Locking mutex 0xb5a0cf48
[11/12 20:22:12.846 AD1]: socketworks.c:500 Unlocking mutex 0xb5a0cf48
[11/12 20:22:12.847 AD1]: socketworks.c:465 Locking mutex 0xb5a0cf48
[11/12 20:22:12.848 AD1]: socketworks.c:500 Unlocking mutex 0xb5a0cf48
[11/12 20:22:12.848 AD1]: socketworks.c:465 Locking mutex 0xb5a0cf48
[11/12 20:22:12.848 AD1]: socketworks.c:500 Unlocking mutex 0xb5a0cf48
[11/12 20:22:12.848 AD1]: socketworks.c:465 Locking mutex 0xb5a0cf48
[11/12 20:22:12.848 AD1]: socketworks.c:500 Unlocking mutex 0xb5a0cf48

**Comment by catalinii** [comment] 2017-12-12 20:43
Is this reproducible at will ?

can you offer remote access if yes ?

**Comment by SeyedGH** [comment] 2017-12-12 21:42
yes tested it a few more times, every time i start second stream, it destroys a mutex from AD0 and reuses it for AD1, then you already know what happen, i can give you remote access..

**Comment by catalinii** [comment] 2017-12-12 22:02
Send me an email to catalinii@yahoo.com with details please.

Include also the 2 streams that you can reproduce it with.

Thanks

**Comment by SeyedGH** [comment] 2017-12-12 22:45
send you an email with remote login details and a extra log.

**Comment by estimadarocha** [comment] 2018-01-15 12:06
@SeyedGH @catalinii now that i finally was able to put again my STB alive i can confirm exact same behaviour that @SeyedGH describe.

Did you @SeyedGH make any progress?

**Comment by iophobia** [comment] 2018-08-10 06:25
Basically reiterating @estimadarocha's question here. Can the FBC tuning be addressed by certain parameters apart from -S x-y:z? Can't seem to get it to work for more than one stream on Uno 4K (arm) (with channels populated and either E2 killed or running) as of now with latest binary from forum.

**Comment by catalinii** [comment] 2018-08-18 20:16
Try -1 0. This works for all the afapters just scanning and epg grabbing fails

**Comment by iophobia** [comment] 2018-08-19 08:43
Thanks, will try. So no way to get both all adapters & epg/scan working at the same time?

**Comment by catalinii** [comment] 2018-08-19 08:45
Not as of today. Hopefully vu will answer to my requests.

**Comment by rayholland** [comment] 2018-10-22 19:21
Hi Catalinii.

Any news on this issue?

I have exactly the same problem as SeyedGH.
My hardware VU+ Uno 4k (FBC tuner) and using the latest minisatip ARM binary from the forum.

Or is there a workaround for now, to have multiple simultaneous streams from different muxes?

Thank you

![afbeelding](https://user-images.githubusercontent.com/33320560/47313877-5f4e0600-d640-11e8-8551-b42adf03c299.png)

**Comment by estimadarocha** [comment] 2018-10-22 20:41
@rayholland no this is not yet solved! at least completely

**Comment by rayholland** [comment] 2018-10-23 12:31
@estimadarocha, thank you for the update. for now i'm using the '-1 0' parameter as catalinii suggested, but i hope this issue will be fixed soon :-)
@Catalinii, if you like i can give you access to my home/test environment for further investigation/testing

**Comment by catalinii** [comment] 2018-10-24 15:33
I have reported the issue to VU but still waiting for a fix.

**Comment by catalinii** [comment] 2019-07-01 15:18
Hey, can someone test the latest images if the situation is better?

**Comment by pbasista** [comment] 2020-04-11 23:59
> Hey, can someone test the latest images if the situation is better?

Yes. I have tried `minisatip` version `1.0.3-ad1fd9f` (currently the latest available pre-built version) for ARM on Vu+ Uno 4K SE with a FBC DVB-S tuner. I have used a custom OpenATV image compiled a few weeks ago with this driver module:

```console
root@vuuno4kse:~ # modinfo dvb_bcm7252sse
filename:       /lib/modules/4.1.20-1.9/extra/dvb-bcm7252sse.ko
license:        Proprietary
author:         Schon
description:    BCM7xxx dvb adapter driver
depends:        procmk
vermagic:       4.1.20-1.9 SMP mod_unload ARMv7 p2v8
root@vuuno4kse:~ # md5sum /lib/modules/4.1.20-1.9/extra/dvb-bcm7252sse.ko                                                                                     
77d5d05295afe5e91766aa4121846a83  /lib/modules/4.1.20-1.9/extra/dvb-bcm7252sse.ko
```

I have launched `minisatip` like this:

```console
root@vuuno4kse:~ # ./minisatip -R html/ -v general,http,socketworks,stream,adapter,satipc,pmt,tables,dvbapi,lock,netceiver,dvbca,axe,socket,utils,dmx,ssdp,dvbb
```

I have used Tvheadend running on the same machine as a client, with the default settings. In there, I have only enabled the first two out of eight Minisatip tuners (which map to eight frontends of a single dvb adapter). Then I have tried to stream two unscrambled channels from two different transponders with the same polarization (V). The reason for that is that I only have one of the device's physical inputs (the upper one) connected to an LNB (universal).

The behavior when only one channel was playing was that sometimes, there were a lot of continuity errors and the video was freezing frequently. Some other times, the video was playing normally. When I tried to stream from the second channel at the same time, sometimes the videos from both channels have started to freeze even more frequently.

It seemed that the freezing behavior depends on the tuners which are enabled. If I have enabled tuners 1 and 3, for instance, then the freezes happened less frequently. But I am not sure if that was only a temporary coincidence or an indication of some dependency between tuner (frontend) number and its capability to get the data from a specific transponder. Also, high-bitrate channels like Astra UHD Demo seem to trigger the continuity errors more often.

Scanning, however, mostly worked. Also EPG grabbing seemed to work correctly, most of the time. The only exception was when two tuners tried to tune to two different transponders with different polarizations at the same time. Then one of the tuners always failed, but then succeeded on another attempt when the other tuner was tuned to a transponder with the same polarization or when it was unused.

I have `minisatip` logs available but I am not sure what to look for in them. Can you perhaps suggest a good list of modules for which it is reasonable to enable the debug level logging?

**Comment by catalinii** [comment] 2020-04-12 06:10
You can try just:

./minisatip -f -l http,dvb -e 7

and upload the logs. If you have just one input this should work good, otherwise use -S

**Comment by pbasista** [comment] 2020-04-12 07:24
Logs from running `./minisatip -l http,dvb -e 7` and trying to watch Astra UHD Demo are here: https://pastebin.com/TTrJ2mRa . There were some continuity errors in Tvheadend, as before.

With multiple adapters enabled, from my previous experiments it seems like the default master/slave configuration for FBC DVB-S adapters (i.e. `-S 2-7:0`) does not work well with this particular device. Or maybe the issue is with the Tvheadend client not being configured correctly (I use the default settings there). I am not sure.

**Comment by pbasista** [comment] 2020-04-12 22:13
I have corrected my previous post. The root cause of the continuity errors seems to have been Tvheadend. Its default configuration disables the "RTP/AVP/TCP transport supported" option within the "Advanced settings" group of the minisatip adapter's parameters. After enabling it, the continuity errors on unscrambled channels have disappeared.

I am now able to use 7 frontends (or minisatip adapters) simultaneously (i.e. `0,2-7`) while having only one input (the upper one, possibly called "A") connected to an LNB. At least in my case, frontend 1 (minisatip adapter 2 when all 8 of them are enabled) seems to only be able to process data from the other input, because all tuning attempts on it always failed while the other physical input was not connected.

**Comment by catalinii** [comment] 2020-04-14 01:32
Yeah if the client supports TCP mode is recommended.

**Comment by StefanS52u1** [comment] 2020-06-07 18:35
Hello pbasista,
i'm also using a vu+ uno 4k se with openatv image.

**Comment by StefanS52u1** [comment] 2020-06-07 18:41
Hello pbasista,
i'm also using a vu+ uno 4k se with openatv image. I'm using the minisatip build from 25. of may 2020. I'm having a DVB-S2 receiver with both input channels connected to an jess matrix. I'm also trying to prepare this box as satip server for my tvh server, but the minisatip server on my vu+ behaves not very well. A lot of failures, continuity errors, frame drops, … **What options do you use to start minisatip**? Do you use the -N option to start it with enigma2 or not?

**Comment by catalinii** [comment] 2020-06-07 19:02
If you do not use/have a CI CAM best way is to run it in standalone mode without enigma2.

**Comment by pbasista** [comment] 2020-06-07 19:22
> What options do you use to start minisatip

I do not have the receiver at hand so I cannot check exactly, but from what I remember, I did not use almost without any options except for disabling the frontend number 1 as described above.

Regarding the continuity errors and similar issues, those were resolved in my case by using TCP mode, as suggested by @catalinii above.

And I use the receiver without Enigma 2 because I do not need it. If running, it can block access to some of the frontends but apart from that I did not notice any issue while experimenting with minisatip while Enigma 2 was running.

**Comment by walterav1984** [comment] 2020-06-16 18:44
Maybe usefull info from other github project "tsduck" where pullrequest mentions possible fix for FBC tuner detection on vuultimo4k with 16frontends with total of 24demuxes dvbS+(dvb-c+dvb-t):

https://github.com/tsduck/tsduck/pull/599
https://github.com/tsduck/tsduck/files/4786006/FBC_new2.txt

**Comment by catalinii** [comment] 2020-06-19 19:38
As I do not have access to such device is hard to know what is the adapter layout. If you provide remote access I can take a look and see if I can make it work

**Comment by Jalle19** [comment] 2022-03-28 19:33
Can this be closed? Was this ever a minisatip issue or was it something that was fixed in the driver? And a false positive caused by not using TCP ik tvheadend apparently 🤷

**Comment by estimadarocha** [comment] 2022-03-28 19:38
Yes it was... But it can be closed now i believe

**Comment by SaulGoodman1337** [comment] 2023-02-24 14:51
Pretty much the same here. It just doesn't want to work right. as soon as I start to want to use multiple tuners everything flies around.
Is there meanwhile times a solution or wants to take care of the problem times one of you?
I will gladly provide remote access.

@catalinii @Jalle19 @lars18th 

I slowly do not know what to do anymore

**Comment by SaulGoodman1337** [comment] 2023-02-24 15:51
Of course, it's in the attachment.
I restarted minisatip with the following command : LD_PRELOAD=/home/root/libdvbcsa.so /home/root/minisatip -f -R /home/root/html/ -x 8080 -j 0:0-1210,1:1-1420,2:2-1680,3:3-2040,4:4-1005,5:5-1050,6:6-1095,7:7-1140 -S 2-7:0 -k -l http > minisatip.log

Then I switched on an FTA channel, BR Fernsehen Süd HD. 
And then I started a second stream, 3Sat HD. And here the problems start directly. -S 1-7:0 is also not working.

[minisatip.log](https://github.com/catalinii/minisatip/files/10825988/minisatip.log)

I hope you can help me, as already said I can give you access.

**Comment by catalinii** [comment] 2023-02-24 17:03
For DVB-C try:
-S 8-16:8 

It seems the adapter 1 (for the second channel) is connected to the second cable instead of the first.
You can try to add to the 3SAT url:
fe=3&freq=....

**Comment by SaulGoodman1337** [comment] 2023-02-24 17:21
> For DVB-C try: -S 8-16:8


With 9-15:8 works. I think that's what you meant?
But I have super many uncorrected block, continunity errors and picture errors. I have attached the log for you. 
[DVBC.log](https://github.com/catalinii/minisatip/files/10827065/DVBC.log)
> 
> It seems the adapter 1 (for the second channel) is connected to the second cable instead of the first. You can try to add to the 3SAT url: fe=3&freq=....

i suspect i can influence this with the "FE supported:" setting in the tvheadend?

**Comment by SaulGoodman1337** [comment] 2023-02-24 17:40
okay interesting. After setting the frontend identifier the whole thing looks much better. However, only one tuner. alos 1xDVB-S and 1xDVB-C work without problems so far. tuning is also unusually fast! But in each case another channel is unfortunately not possible. I have attached a log. here in the example dvbs.
i have tuned 3Sat HD and then ARD alpha HD.

[two_dvb_s_channels.log](https://github.com/catalinii/minisatip/files/10827241/two_dvb_s_channels.log)

**Comment by SaulGoodman1337** [comment] 2023-02-25 08:44
So, I have now tried again a bit and use only the following command to start minisatip.

> LD_PRELOAD=/home/root/libdvbcsa.so /home/root/minisatip -f -R -i /home/root/html/ -x 8080 -j 0:0-*1210,1:1-*1420,2:2-1680,3:3-2040,4:4-1005,5:5-1050,6:6-1095,7:7-1140 -S 2-7:0 -S 9-15:8 -l http --adapter-timeout *:0 -1 2 -k -o <IP>:<PORT> -E

I have never had such fast switching times, also I have no more errors. BUT the whole works only with one tuner each of dvb-c and dvb-s without problems. as soon as I activate more tuners come the errors, if the tuning then still works at all. 
Do you have any ideas here?

**Comment by catalinii** [comment] 2023-02-26 05:18
You should try to NOT use adapter 1 because is mapped to the second input. Use any other adapter except 1 for the second channel.
The other option is to add the following arguments:
-e 0,2

**Comment by SaulGoodman1337** [comment] 2023-02-26 07:46
> You should try to NOT use adapter 1 because is mapped to the second input. Use any other adapter except 1 for the second channel. The other option is to add the following arguments: -e 0,2

doesn't get me anywhere either. as soon as more than one tuner is used or i start a scan, i can't tune any channels.

**Comment by catalinii** [comment] 2023-02-28 02:14
Can you upload a new log with -e 0,2 ?

**Comment by Jalle19** [comment] 2024-08-07 11:01
Closing this again due to inactivity

**Closed by Jalle19** 2024-08-07 11:01 UTC
