### ISSUE TITLE
doesnt run on mips and openwrt 18.06 stable release

### ISSUE THREAD

**Issue by Ntemis** [catalinii/minisatip#450] opened 2018-08-07 15:35 UTC
./minisatip: line 1: ELF@i@4ktp4: not found
./minisatip: line 4: syntax error: unterminated quoted string
 Can you please add it to the database as .ipk installation?

**Comment by Ntemis** [comment] 2018-08-07 15:36
Binary was taken from here:
https://minisatip.org/forum/viewtopic.php?t=371
"minisatip_mips_openwrt_dvbcsa.zip"

**Comment by Ntemis** [comment] 2018-08-13 14:58
I hope you can add it to the openwrt distro as you did with the enigma 2 boxes on openatv!
People really need to be able to use their routers as minisatip server for dvb-t devices since those routers are usually powered ON 24h a day. Myself included :)
My router has 1 x v3.0 USB and 2 x v2.0 USB ports that are eager to be used even with USB hubs if needed.

**Comment by catalinii** [comment] 2018-08-18 20:15
Yes I think the best way forward is to include minisatip in openwrt. i will close this one as duplicate of #446

**Closed by catalinii** 2018-08-18 20:15 UTC
