### ISSUE TITLE
SAT>IP Spec changes

### ISSUE THREAD

**Issue by 9000h** [catalinii/minisatip#14] opened 2015-01-16 14:17 UTC
Hi there is a new Version as mentioned out at SES

http://www.satip.info/sites/satip/files/resource/satip_specification_release_notes_version_1_2_2.txt
http://www.satip.info/sites/satip/files/resource/satip_specification_version_1_2_2.pdf

From the release notes:
would be a nice feature:
Section 3.4.1 added possibility for a SAT>IP server to provide a URL to a Channel List (local or remote) 

may important:
Editorial
Section 3.3.2 added missing ssdp:byebye to the NTS header value

**Comment by catalinii** [comment] 2015-01-16 14:40
For the channel list, i can add a command line option with url to the playlist, is that what you have in mind?

I think at this point I do not detect the device id from the network (or store it). Do you need this behaviour changed?

**Comment by 9000h** [comment] 2015-01-16 14:53
as the new version of the spec says, only devices implement multicast need to handle device id's
no I do not need this

**Comment by 9000h** [comment] 2015-01-16 14:58
there is no important need for the channel list, it's more a nice to have jet.

maybe more interesting would be the streaming via http like the Telestar Digibit R1...
with this in mind the channel list url would make sense to me, every TV/APP could then used to watch very easy.

**Comment by catalinii** [comment] 2015-01-17 09:02
Well most of the http streaming is done, but yes maybe I should get on that at one point...
The other problem with this is that I will need a static list since I do not plan to implement scanning at this point (too much hassle and there are another products that does it)

**Comment by catalinii** [comment] 2015-01-19 07:05
Please test this and let me know how it works.

Thanks

**Comment by 9000h** [comment] 2015-01-19 22:55
so I did try with smplayer but it crashes at some point
root@yavdr:/home/yavdr/satip/minisatip-master# gdb ./minisatip
GNU gdb (Ubuntu/Linaro 7.4-2012.04-0ubuntu2.1) 7.4-2012.04
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
For bug reporting instructions, please see:
<http://bugs.launchpad.net/gdb-linaro/>...
Reading symbols from /home/yavdr/satip/minisatip-master/minisatip...done.
(gdb) r -l -l -l -f
Starting program: /home/yavdr/satip/minisatip-master/minisatip -l -l -l -f
warning: no loadable sections found in added symbol-file system-supplied DSO at 0x7ffff7ffa000
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Starting minisatip version 0.1.8, dvbapi version: 0504
[Mon Jan 19 23:46:46.000 2015]: New UDP socket 7 bound to 0.0.0.0:1900
[Mon Jan 19 23:46:46.000 2015]: setting multicast for 239.255.255.250
[Mon Jan 19 23:46:46.000 2015]: New UDP socket 8 bound to 239.255.255.250:1900
[Mon Jan 19 23:46:46.000 2015]: New UDP socket 11 bound to 0.0.0.0:5500
[Mon Jan 19 23:46:46.000 2015]: New UDP socket 12 bound to 0.0.0.0:5501
[Mon Jan 19 23:46:46.000 2015]: sockets_add: handle 7 (type 0) returning socket index 0 [0.0.0.0:0]
[Mon Jan 19 23:46:46.000 2015]: sockets_add: handle 8 (type 0) returning socket index 1 [0.0.0.0:0]
[Mon Jan 19 23:46:46.000 2015]: sockets_add: handle 9 (type 2) returning socket index 2 [0.0.0.0:0]
[Mon Jan 19 23:46:46.000 2015]: sockets_add: handle 10 (type 2) returning socket index 3 [0.0.0.0:0]
[Mon Jan 19 23:46:46.000 2015]: starting init_hw 0
[Mon Jan 19 23:46:46.001 2015]: trying to open [0] adapter 0 and frontend 0
adapter.c:103 allocation_wrapper malloc allocated 9222 bytes at 0x628cb0
[Mon Jan 19 23:46:46.001 2015]: opened DVB adapter 0 fe:13 dvr:14
[Mon Jan 19 23:46:46.001 2015]: Done setting DVR buffer to 5775360 bytes
[Mon Jan 19 23:46:46.001 2015]: deleting pids on adapter 0, sid -1, pids=NULL
[Mon Jan 19 23:46:46.018 2015]: sockets_add: handle 14 (type 5) returning socket index 4 [0.0.0.0:0]
[Mon Jan 19 23:46:46.018 2015]: done opening adapter 0 fe_sys 6
[Mon Jan 19 23:46:46.018 2015]: trying to open [1] adapter 0 and frontend 1
adapter.c:103 allocation_wrapper malloc allocated 9222 bytes at 0x62b0c0
[Mon Jan 19 23:46:46.019 2015]: opened DVB adapter 1 fe:15 dvr:16
[Mon Jan 19 23:46:46.019 2015]: Done setting DVR buffer to 5775360 bytes
[Mon Jan 19 23:46:46.019 2015]: deleting pids on adapter 1, sid -1, pids=NULL
[Mon Jan 19 23:46:46.733 2015]: sockets_add: handle 16 (type 5) returning socket index 5 [0.0.0.0:0]
[Mon Jan 19 23:46:46.733 2015]: done opening adapter 1 fe_sys 6
[Mon Jan 19 23:46:46.733 2015]: done init_hw 1
Initializing with 2 devices
[Mon Jan 19 23:46:47.934 2015]: ssdp_discovery fd: 7 -> NOTIFY * HTTP/1.1
HOST: 239.255.255.250:1900
CACHE-CONTROL: max-age=1800
LOCATION: http://192.168.178.101:8080/desc.xml
NT: upnp:rootdevice
NTS: ssdp:alive 
SERVER: Linux/1.0 UPnP/1.1 IDL4K/1.2
USN: uuid:11223344-9999-0000-b7ae-00224d9d3805::upnp:rootdevice
BOOTID.UPNP.ORG: 9
CONFIGID.UPNP.ORG: 0
DEVICEID.SES.COM: 6


[Mon Jan 19 23:46:51.490 2015]: sockets_add: handle 18 (type 1) returning socket index 6 [192.168.178.101:47987]
[Mon Jan 19 23:46:51.490 2015]: read RTSP (from handle 18 sock_id 6):
GET /?src=1&freq=12188&sr=27500&pol=h&msys=dvbs&pids=0,44,163,104,106 HTTP/1.0
Host: 192.168.178.101:8080
User-Agent: MPlayer UNKNOWN
Icy-MetaData: 1
Connection: close


[Mon Jan 19 23:46:51.490 2015]: starting init_hw 1
[Mon Jan 19 23:46:51.490 2015]: detect_dvb_parameters (S)-> src=1&freq=12188&sr=27500&pol=h&msys=dvbs&pids=0,44,163,104,106
[Mon Jan 19 23:46:51.490 2015]: detect_dvb_parameters (E) -> src=1, fe=-1, freq=12188000, sr=27500000, pol=72, ro=-1, msys=5, mtype=-1, pltf=-1, bw=-1, inv=-1, pids=0,44,163,104,106 - apids=NULL - dpids=NULL
[Mon Jan 19 23:46:51.490 2015]: Setup stream -1 parameters, sock_id 6, handle 18
stream.c:277 allocation_wrapper malloc allocated 321 bytes at 0x628500
stream.c:279 allocation_wrapper malloc allocated 321 bytes at 0x62d4d0
stream.c:281 allocation_wrapper malloc allocated 321 bytes at 0x62d620
stream.c:283 allocation_wrapper malloc allocated 1326 bytes at 0x62d770
[Mon Jan 19 23:46:51.490 2015]: copy_dvb_param start -> src=0, fe=0, freq=0, sr=0, pol=, ro=3, msys=0, mtype=0, pltf=2, bw=8000000, inv=2, pids=NULL, apids=NULL, dpids=NULL
[Mon Jan 19 23:46:51.490 2015]: copy_dvb_parameters -> src=1, fe=0, freq=12188000, sr=27500000, pol=H, ro=3, msys=5, mtype=0, pltf=2, bw=8000000, inv=2, pids=0,44,163,104,106, apids=NULL, dpids=NULL
[Mon Jan 19 23:46:51.490 2015]: Setup stream done: sid: 0 (e:1) for sock 6 handle 18
[Mon Jan 19 23:46:51.490 2015]: Play for stream 0, adapter -1, sock_id 6 handle 18
[Mon Jan 19 23:46:51.490 2015]: get free adapter -1 - a[0] => e:1 m:-1 sid_cnt:0 f:0

[Mon Jan 19 23:46:51.490 2015]: Got adapter 0 on socket 6
[Mon Jan 19 23:46:51.490 2015]: set adapter 0 for stream 0 m:0 s:1
[Mon Jan 19 23:46:51.490 2015]: setting DVB parameters for adapter 0 - master_sid 0 sid 0 old f:0
[Mon Jan 19 23:46:51.490 2015]: deleting pids on adapter 0, sid -1, pids=NULL
[Mon Jan 19 23:46:51.490 2015]: deleting pids on adapter 0, sid -1, pids=NULL
[Mon Jan 19 23:46:51.490 2015]: copy_dvb_param start -> src=0, fe=0, freq=0, sr=0, pol=, ro=3, msys=6, mtype=0, pltf=2, bw=8000000, inv=2, pids=NULL, apids=NULL, dpids=NULL
[Mon Jan 19 23:46:51.490 2015]: copy_dvb_parameters -> src=1, fe=0, freq=12188000, sr=27500000, pol=H, ro=3, msys=5, mtype=0, pltf=2, bw=8000000, inv=2, pids=0,44,163,104,106, apids=NULL, dpids=NULL
[Mon Jan 19 23:46:52.910 2015]: tunning to 12188000(1588000) sr:27500000 fec:FEC_AUTO delsys:SYS_DVBS mod:qpsk rolloff:ROLLOFF_AUTO pilot:PILOT_AUTO
[Mon Jan 19 23:46:52.910 2015]: setting filter on PID 0 for fd 19
[Mon Jan 19 23:46:52.910 2015]: setting filter on PID 44 for fd 20
[Mon Jan 19 23:46:52.910 2015]: setting filter on PID 163 for fd 21
[Mon Jan 19 23:46:52.910 2015]: setting filter on PID 104 for fd 22
[Mon Jan 19 23:46:52.910 2015]: setting filter on PID 106 for fd 23
[Mon Jan 19 23:46:52.910 2015]: reply -> 18 (CL:0) :
HTTP/1.0 200 OK
Cseq: 0



[Mon Jan 19 23:46:52.925 2015]: no data sent for more than 1s sid: 0 for 0.0.0.0:0
[Mon Jan 19 23:46:52.537 2015]: get_signal took 142 ms for adapter 0 handle 13 (status: 1, ber: 0, strength:45874, snr: 48453, max_strength: 45874, max_snr: 48453)
[Mon Jan 19 23:46:52.537 2015]: bandwidth 311KB/s, total bandwidth: 0 MB, HD: 0 MB, SD: 0 MB, Other: 0 MB, notify: 0
[Mon Jan 19 23:46:53.539 2015]: bandwidth 710KB/s, total bandwidth: 1 MB, HD: 0 MB, SD: 0 MB, Other: 0 MB, notify: 0
[Mon Jan 19 23:46:54.549 2015]: bandwidth 548KB/s, total bandwidth: 1 MB, HD: 0 MB, SD: 1 MB, Other: 0 MB, notify: 0
[Mon Jan 19 23:46:55.559 2015]: bandwidth 647KB/s, total bandwidth: 2 MB, HD: 0 MB, SD: 1 MB, Other: 0 MB, notify: 0
[Mon Jan 19 23:46:56.570 2015]: bandwidth 593KB/s, total bandwidth: 2 MB, HD: 0 MB, SD: 2 MB, Other: 0 MB, notify: 0
[Mon Jan 19 23:46:57.580 2015]: bandwidth 629KB/s, total bandwidth: 3 MB, HD: 0 MB, SD: 3 MB, Other: 0 MB, notify: 0
[Mon Jan 19 23:46:58.590 2015]: bandwidth 656KB/s, total bandwidth: 4 MB, HD: 0 MB, SD: 3 MB, Other: 0 MB, notify: 0
[Mon Jan 19 23:46:59.600 2015]: bandwidth 638KB/s, total bandwidth: 4 MB, HD: 0 MB, SD: 4 MB, Other: 0 MB, notify: 0
[Mon Jan 19 23:47:10.648 2015]: bandwidth 134KB/s, total bandwidth: 4 MB, HD: 0 MB, SD: 4 MB, Other: 0 MB, notify: 0
[Mon Jan 19 23:47:10.648 2015]: no data sent for more than 1s sid: 0 for 0.0.0.0:0
[Mon Jan 19 23:47:11.514 2015]: Reading max size for the last 100 buffers
[Mon Jan 19 23:47:12.433 2015]: bandwidth 1214KB/s, total bandwidth: 6 MB, HD: 1 MB, SD: 4 MB, Other: 0 MB, notify: 0
[Mon Jan 19 23:47:13.473 2015]: bandwidth 512KB/s, total bandwidth: 6 MB, HD: 1 MB, SD: 4 MB, Other: 0 MB, notify: 0
[Mon Jan 19 23:47:13.473 2015]: no data sent for more than 1s sid: 0 for 0.0.0.0:0
[Mon Jan 19 23:47:13.473 2015]: Reading max size for the last 200 buffers
[Mon Jan 19 23:47:14.303 2015]: Reading max size for the last 300 buffers
[Mon Jan 19 23:47:15.601 2015]: bandwidth 1016KB/s, total bandwidth: 7 MB, HD: 2 MB, SD: 4 MB, Other: 0 MB, notify: 0
[Mon Jan 19 23:47:15.601 2015]: no data sent for more than 1s sid: 0 for 0.0.0.0:0
[Mon Jan 19 23:47:17.105 2015]: bandwidth 449KB/s, total bandwidth: 8 MB, HD: 2 MB, SD: 5 MB, Other: 0 MB, notify: 0
[Mon Jan 19 23:47:17.105 2015]: no data sent for more than 1s sid: 0 for 0.0.0.0:0
[Mon Jan 19 23:47:17.107 2015]: Reading max size for the last 400 buffers
[Mon Jan 19 23:47:18.725 2015]: bandwidth 512KB/s, total bandwidth: 8 MB, HD: 2 MB, SD: 5 MB, Other: 0 MB, notify: 0
[Mon Jan 19 23:47:18.725 2015]: no data sent for more than 1s sid: 0 for 0.0.0.0:0
[Mon Jan 19 23:47:20.668 2015]: bandwidth 512KB/s, total bandwidth: 9 MB, HD: 2 MB, SD: 6 MB, Other: 0 MB, notify: 0
[Mon Jan 19 23:47:20.668 2015]: select_and_execute[4]: Error on socket 14 (sid:0) from 0.0.0.0:0 - type dvr failure 75:EOVERFLOW
[Mon Jan 19 23:47:20.668 2015]: no data sent for more than 1s sid: 0 for 0.0.0.0:0
[Mon Jan 19 23:47:22.601 2015]: bandwidth 640KB/s, total bandwidth: 9 MB, HD: 2 MB, SD: 7 MB, Other: 0 MB, notify: 0
[Mon Jan 19 23:47:22.601 2015]: no data sent for more than 1s sid: 0 for 0.0.0.0:0
[Mon Jan 19 23:47:22.601 2015]: sockets_del: 6 -> handle 18, sid 0
[Mon Jan 19 23:47:22.601 2015]: Closing stream 0
[Mon Jan 19 23:47:22.601 2015]: closing stream 0
[Mon Jan 19 23:47:22.601 2015]: closed adapter 0 for stream 0 m:-1 s:0
[Mon Jan 19 23:47:22.601 2015]: deleting pids on adapter 0, sid 0, pids=NULL
[Mon Jan 19 23:47:22.601 2015]: clearing filters on PID 163 FD 21
[Mon Jan 19 23:47:22.601 2015]: clearing filters on PID 106 FD 23
[Mon Jan 19 23:47:22.601 2015]: clearing filters on PID 104 FD 22
[Mon Jan 19 23:47:22.601 2015]: clearing filters on PID 0 FD 19
[Mon Jan 19 23:47:22.601 2015]: clearing filters on PID 44 FD 20
[Mon Jan 19 23:47:22.601 2015]: closing adapter 0  -> fe:13 dvr:14
[Mon Jan 19 23:47:22.601 2015]: deleting pids on adapter 0, sid -1, pids=NULL
[Mon Jan 19 23:47:22.601 2015]: sockets_del: 4 -> handle 14, sid 0
[Mon Jan 19 23:47:22.601 2015]: closing DVR socket -1 pos 4 aid 0
[Mon Jan 19 23:47:22.602 2015]: sockets_del: 4 Last open socket is at index 5 current_handle 14
[Mon Jan 19 23:47:22.602 2015]: done closing adapter 0
[Mon Jan 19 23:47:22.602 2015]: closed stream 0
[Mon Jan 19 23:47:22.602 2015]: sockets_del: 6 Last open socket is at index 5 current_handle 18
[Mon Jan 19 23:47:46.828 2015]: sockets_del: 5 -> handle 16, sid 1
[Mon Jan 19 23:47:46.828 2015]: closing DVR socket -1 pos 5 aid 1
[Mon Jan 19 23:47:46.828 2015]: closing adapter 1  -> fe:15 dvr:16
[Mon Jan 19 23:47:46.828 2015]: deleting pids on adapter 1, sid -1, pids=NULL
[Mon Jan 19 23:47:46.828 2015]: sockets_del: 5 -> handle -1, sid 1
[Mon Jan 19 23:47:46.828 2015]: done closing adapter 1
[Mon Jan 19 23:47:46.828 2015]: sockets_del: 5 Last open socket is at index 3 current_handle 16

[Mon Jan 19 23:48:37.749 2015]: sockets_add: handle 13 (type 1) returning socket index 4 [192.168.178.101:48002]
[Mon Jan 19 23:48:37.749 2015]: read RTSP (from handle 13 sock_id 4):
GET /?src=1&freq=12188&sr=27500&pol=h&msys=dvbs&pids=0,44,163,104,106 HTTP/1.0
Host: 192.168.178.101:8080
User-Agent: MPlayer UNKNOWN
Icy-MetaData: 1
Connection: close


[Mon Jan 19 23:48:37.749 2015]: starting init_hw 0
[Mon Jan 19 23:48:37.749 2015]: trying to open [0] adapter 0 and frontend 0
[Mon Jan 19 23:48:37.749 2015]: opened DVB adapter 0 fe:14 dvr:15
[Mon Jan 19 23:48:37.750 2015]: Done setting DVR buffer to 5775360 bytes
[Mon Jan 19 23:48:37.750 2015]: deleting pids on adapter 0, sid -1, pids=NULL
[Mon Jan 19 23:48:37.765 2015]: sockets_add: handle 15 (type 5) returning socket index 5 [0.0.0.0:0]
[Mon Jan 19 23:48:37.765 2015]: done opening adapter 0 fe_sys 6
[Mon Jan 19 23:48:37.765 2015]: trying to open [1] adapter 0 and frontend 1
[Mon Jan 19 23:48:37.765 2015]: opened DVB adapter 1 fe:16 dvr:18
[Mon Jan 19 23:48:37.766 2015]: Done setting DVR buffer to 5775360 bytes
[Mon Jan 19 23:48:37.766 2015]: deleting pids on adapter 1, sid -1, pids=NULL
[Mon Jan 19 23:48:37.781 2015]: sockets_add: handle 18 (type 5) returning socket index 6 [0.0.0.0:0]
[Mon Jan 19 23:48:37.781 2015]: done opening adapter 1 fe_sys 6
[Mon Jan 19 23:48:37.781 2015]: done init_hw 1
[Mon Jan 19 23:48:37.781 2015]: detect_dvb_parameters (S)-> src=1&freq=12188&sr=27500&pol=h&msys=dvbs&pids=0,44,163,104,106
[Mon Jan 19 23:48:37.781 2015]: detect_dvb_parameters (E) -> src=1, fe=-1, freq=12188000, sr=27500000, pol=72, ro=-1, msys=5, mtype=-1, pltf=-1, bw=-1, inv=-1, pids=0,44,163,104,106 - apids=NULL - dpids=NULL
[Mon Jan 19 23:48:37.781 2015]: Setup stream -1 parameters, sock_id 4, handle 13
[Mon Jan 19 23:48:37.781 2015]: copy_dvb_param start -> src=0, fe=0, freq=0, sr=0, pol=, ro=3, msys=0, mtype=0, pltf=2, bw=8000000, inv=2, pids=NULL, apids=NULL, dpids=NULL
[Mon Jan 19 23:48:37.781 2015]: copy_dvb_parameters -> src=1, fe=0, freq=12188000, sr=27500000, pol=H, ro=3, msys=5, mtype=0, pltf=2, bw=8000000, inv=2, pids=0,44,163,104,106, apids=NULL, dpids=NULL
[Mon Jan 19 23:48:37.781 2015]: Setup stream done: sid: 0 (e:1) for sock 4 handle 13
[Mon Jan 19 23:48:37.781 2015]: Play for stream 0, adapter -1, sock_id 4 handle 13
[Mon Jan 19 23:48:37.781 2015]: get free adapter -1 - a[0] => e:1 m:-1 sid_cnt:0 f:0

[Mon Jan 19 23:48:37.781 2015]: Got adapter 0 on socket 4
[Mon Jan 19 23:48:37.781 2015]: set adapter 0 for stream 0 m:0 s:1
[Mon Jan 19 23:48:37.781 2015]: setting DVB parameters for adapter 0 - master_sid 0 sid 0 old f:0
[Mon Jan 19 23:48:37.781 2015]: deleting pids on adapter 0, sid -1, pids=NULL
[Mon Jan 19 23:48:37.781 2015]: deleting pids on adapter 0, sid -1, pids=NULL
[Mon Jan 19 23:48:37.781 2015]: copy_dvb_param start -> src=0, fe=0, freq=0, sr=0, pol=, ro=3, msys=6, mtype=0, pltf=2, bw=8000000, inv=2, pids=NULL, apids=NULL, dpids=NULL
[Mon Jan 19 23:48:37.781 2015]: copy_dvb_parameters -> src=1, fe=0, freq=12188000, sr=27500000, pol=H, ro=3, msys=5, mtype=0, pltf=2, bw=8000000, inv=2, pids=0,44,163,104,106, apids=NULL, dpids=NULL
[Mon Jan 19 23:48:38.186 2015]: tunning to 12188000(1588000) sr:27500000 fec:FEC_AUTO delsys:SYS_DVBS mod:qpsk rolloff:ROLLOFF_AUTO pilot:PILOT_AUTO
[Mon Jan 19 23:48:38.186 2015]: setting filter on PID 0 for fd 19
[Mon Jan 19 23:48:38.186 2015]: setting filter on PID 44 for fd 20
[Mon Jan 19 23:48:38.186 2015]: setting filter on PID 163 for fd 21
[Mon Jan 19 23:48:38.186 2015]: setting filter on PID 104 for fd 22
[Mon Jan 19 23:48:38.186 2015]: setting filter on PID 106 for fd 23
[Mon Jan 19 23:48:38.186 2015]: reply -> 13 (CL:0) :
HTTP/1.0 200 OK
Cseq: 0
????????


[Mon Jan 19 23:48:38.805 2015]: get_signal took 143 ms for adapter 0 handle 14 (status: 1, ber: 0, strength:45874, snr: 48430, max_strength: 45874, max_snr: 48453)
[Mon Jan 19 23:48:38.805 2015]: bandwidth 242KB/s, total bandwidth: 9 MB, HD: 2 MB, SD: 7 MB, Other: 0 MB, notify: 0
[Mon Jan 19 23:48:39.806 2015]: bandwidth 881KB/s, total bandwidth: 10 MB, HD: 3 MB, SD: 7 MB, Other: 0 MB, notify: 0
[Mon Jan 19 23:48:40.816 2015]: bandwidth 728KB/s, total bandwidth: 11 MB, HD: 3 MB, SD: 7 MB, Other: 0 MB, notify: 0
[Mon Jan 19 23:48:41.826 2015]: bandwidth 755KB/s, total bandwidth: 12 MB, HD: 3 MB, SD: 8 MB, Other: 0 MB, notify: 0
[Mon Jan 19 23:48:42.836 2015]: bandwidth 494KB/s, total bandwidth: 12 MB, HD: 3 MB, SD: 9 MB, Other: 0 MB, notify: 0
[Mon Jan 19 23:48:43.847 2015]: bandwidth 593KB/s, total bandwidth: 13 MB, HD: 3 MB, SD: 9 MB, Other: 0 MB, notify: 0
[Mon Jan 19 23:48:44.857 2015]: bandwidth 719KB/s, total bandwidth: 14 MB, HD: 3 MB, SD: 10 MB, Other: 0 MB, notify: 0

Program received signal SIGPIPE, Broken pipe.
0x00007ffff76e2c3b in writev () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) 
(gdb) bt
#0  0x00007ffff76e2c3b in writev () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00000000004096f8 in flush_streami (sid=0x61c160, ctime=119495)
    at stream.c:411
#2  0x0000000000409d37 in read_dmx (s=0x619da0) at stream.c:500
#3  0x0000000000406a7a in select_and_execute () at socketworks.c:402
#4  0x00000000004049c7 in main (argc=5, argv=0x7fffffffe6a8) at minisatip.c:780
(gdb) print s
$3 = {{sock = 7, sa = {sin_family = 2, sin_port = 27655, sin_addr = {
        s_addr = 1706207424}, sin_zero = "\000\000\000\000\000\000\000"}, 
    action = 0x40421b <ssdp_reply>, close = 0, 
    timeout = 0x403fb0 <ssdp_discovery>, type = 0, sid = -1, rtime = 934, 
    buf = 0x7fffffffdd40 "GET", lbuf = 2000, rlen = 331, close_sec = 1800000, 
    sock_id = 0, err = 0, flags = 0}, {sock = 8, sa = {sin_family = 2, 
      sin_port = 27655, sin_addr = {s_addr = 1706207424}, 
      sin_zero = "\000\000\000\000\000\000\000"}, 
    action = 0x40421b <ssdp_reply>, close = 0, 
    timeout = 0x403fb0 <ssdp_discovery>, type = 0, sid = -1, rtime = 934, 
    buf = 0x7fffffffdd40 "GET", lbuf = 2000, rlen = 331, close_sec = 0, 
    sock_id = 1, err = 0, flags = 0}, {sock = 9, sa = {sin_family = 0, 
      sin_port = 0, sin_addr = {s_addr = 0}, 
      sin_zero = "\000\000\000\000\000\000\000"}, 
    action = 0x404416 <new_rtsp>, close = 0, timeout = 0x403ed7 <close_http>, 
    type = 2, sid = -1, rtime = 0, buf = 0x0, lbuf = 0, rlen = 0, 
    close_sec = 0, sock_id = 2, err = 0, flags = 0}, {sock = 10, sa = {
      sin_family = 0, sin_port = 0, sin_addr = {s_addr = 0}, 
      sin_zero = "\000\000\000\000\000\000\000"}, 
    action = 0x40444e <new_http>, close = 0, timeout = 0x403ed7 <close_http>, 
    type = 2, sid = -1, rtime = 111749, buf = 0x7fffffffdd40 "GET", 
    lbuf = 2000, rlen = 0, close_sec = 0, sock_id = 3, err = 0, flags = 0}, {
    sock = 13, sa = {sin_family = 2, sin_port = 33467, sin_addr = {
---Type <return> to continue, or q <return> to quit---
        s_addr = 1706207424}, sin_zero = "\000\000\000\000\000\000\000"}, 
    action = 0x4037fe <read_http>, close = 0x403ed7 <close_http>, 
    timeout = 0x40a227 <stream_timeout>, type = 3, sid = 0, rtime = 111749, 
    buf = 0x7fffffffdd40 "GET", lbuf = 2000, rlen = 0, close_sec = 200, 
    sock_id = 4, err = 0, flags = 0}, {sock = 15, sa = {sin_family = 0, 
      sin_port = 0, sin_addr = {s_addr = 0}, 
      sin_zero = "\000\000\000\000\000\000\000"}, 
    action = 0x409788 <read_dmx>, close = 0x40d46b <close_adapter_for_socket>, 
    timeout = 0, type = 5, sid = 0, rtime = 119495, buf = 0x628cb0 "G", 
    lbuf = 9212, rlen = 0, close_sec = 60000, sock_id = 5, err = 0, 
    flags = 0}, {sock = 18, sa = {sin_family = 0, sin_port = 0, sin_addr = {
        s_addr = 0}, sin_zero = "\000\000\000\000\000\000\000"}, 
    action = 0x409788 <read_dmx>, close = 0x40d46b <close_adapter_for_socket>, 
    timeout = 0, type = 5, sid = 1, rtime = 111781, buf = 0x62b0c0 "", 
    lbuf = 9212, rlen = 0, close_sec = 60000, sock_id = 6, err = 0, 
    flags = 0}, {sock = -1, sa = {sin_family = 0, sin_port = 0, sin_addr = {
        s_addr = 0}, sin_zero = "\000\000\000\000\000\000\000"}, action = 0, 
    close = 0, timeout = 0, type = 0, sid = 0, rtime = 0, buf = 0x0, lbuf = 0, 
    rlen = 0, close_sec = 0, sock_id = 0, err = 0, 
    flags = 0} <repeats 93 times>}
(gdb) ^CQuit

**Comment by catalinii** [comment] 2015-01-22 07:48
Can you reproduce this ?
Tried today with  mplyer same url and it is working for me.

**Comment by catalinii** [comment] 2015-01-28 04:43
I will close this as I did some work around it,

if you see this again please let me know

**Closed by catalinii** 2015-01-28 04:43 UTC
