### ISSUE TITLE
Signal STR reported incorrectly in web interface

### ISSUE THREAD

**Issue by mark-royds** [catalinii/minisatip#902] opened 2021-10-19 23:25 UTC
Using dvbv5-zap I tune a transponder and get a signal strength report of 106.5%:

```
root@zgemmah2s:~# dvbv5-zap -a 0 -c dvb_channel.conf -f 0 "BBC ONE HD"
WARNING  Ignoring device /dev/dvb/adapter0/audio0
WARNING  Ignoring device /dev/dvb/adapter0/video0
using demux 'dvb0.demux0'
reading channels from file 'dvb_channel.conf'
tuning to 10847000 Hz
video pid 5400
  dvb_set_pesfilter 5400
dvb_dev_set_bufsize: buffer set to 6160384
audio pid 5402
  dvb_set_pesfilter 5402
       (0x00)
Lock   (0x1f) Signal= 106.50% C/N= 17.28dB
          Layer A: C/N= 86.62%
Lock   (0x1f) Signal= 106.50% C/N= 17.15dB
          Layer A: C/N= 85.96%

```

If I tune the same channel using minisatip, the web interface reports the signal strength as 6%

The --multiplier option cannot be used to correct this problem as it is applied after the rollover/truncation occurs.  EG --multiplier 0:0.5-0.5 gives a signal strength of 3%

**Comment by lars18th** [comment] 2022-01-21 13:49
Hi @mark-royds ,

Please, could you close this issue? We're targeting it in #911. So, I suggest to continue there.

**Comment by Jalle19** [comment] 2022-08-04 13:11
Closing as duplicate of #911 , the root cause could be the same

**Closed by Jalle19** 2022-08-04 13:11 UTC
