### ISSUE TITLE
fill_sockaddr: gethostbyname(localhost): Too many open files

### ISSUE THREAD

**Issue by 3PO** [catalinii/minisatip#113] opened 2015-04-12 06:42 UTC
Hi,

with the latest commit (c3854bb) i find Messages like.

>fill_sockaddr: gethostbyname(localhost): Too many open files

in the syslog:

https://bpaste.net/show/1c26c4b39d7d

minisatip is started with: 

>-g -l -o localhost:4444

**Comment by catalinii** [comment] 2015-04-12 08:46
Hi,

Can you upload the full log?

Thanks

**Comment by 3PO** [comment] 2015-04-12 09:34
Logfile:  --> http://dreipo.cc/logs/log.tgz

**Comment by catalinii** [comment] 2015-04-13 15:21
I think I know what this issue is.
Will fix it in the next commit.

**Comment by catalinii** [comment] 2015-04-20 09:40
Is this fixed in the last commit?

Thanks

**Comment by 3PO** [comment] 2015-04-20 17:01
Sorry, but i've disabled satip at the moment,
 Because of this Problem -> https://github.com/catalinii/minisatip/issues/107 , satip is not very usefully with the VDR.

**Comment by catalinii** [comment] 2015-04-29 12:20
Hi 3PO,

I will close this case as I believe the issue is fixed .
If you still get the issue if you test again please reopen it.

Thanks

**Closed by catalinii** 2015-04-29 12:20 UTC
